// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/apikey"
	"github.com/TokenFlux/TokenRouter/ent/apikeycompositegroup"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
	"github.com/TokenFlux/TokenRouter/ent/provider"
	"github.com/TokenFlux/TokenRouter/ent/usagelog"
	"github.com/TokenFlux/TokenRouter/ent/user"
	"github.com/TokenFlux/TokenRouter/internal/protocol"
	"github.com/TokenFlux/TokenRouter/internal/routing/accessview"
	"github.com/TokenFlux/TokenRouter/internal/scheduler/policy"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupUpdate) SetUpdatedAt(v time.Time) *GroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GroupUpdate) SetDeletedAt(v time.Time) *GroupUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableDeletedAt(v *time.Time) *GroupUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GroupUpdate) ClearDeletedAt() *GroupUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetLocalization sets the "localization" field.
func (_u *GroupUpdate) SetLocalization(v accessview.GroupLocalization) *GroupUpdate {
	_u.mutation.SetLocalization(v)
	return _u
}

// SetNillableLocalization sets the "localization" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableLocalization(v *accessview.GroupLocalization) *GroupUpdate {
	if v != nil {
		_u.SetLocalization(*v)
	}
	return _u
}

// ClearLocalization clears the value of the "localization" field.
func (_u *GroupUpdate) ClearLocalization() *GroupUpdate {
	_u.mutation.ClearLocalization()
	return _u
}

// SetName sets the "name" field.
func (_u *GroupUpdate) SetName(v string) *GroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableName(v *string) *GroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupUpdate) SetDescription(v string) *GroupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableDescription(v *string) *GroupUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupUpdate) ClearDescription() *GroupUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *GroupUpdate) SetRateMultiplier(v float64) *GroupUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableRateMultiplier(v *float64) *GroupUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *GroupUpdate) AddRateMultiplier(v float64) *GroupUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetIsExclusive sets the "is_exclusive" field.
func (_u *GroupUpdate) SetIsExclusive(v bool) *GroupUpdate {
	_u.mutation.SetIsExclusive(v)
	return _u
}

// SetNillableIsExclusive sets the "is_exclusive" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableIsExclusive(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetIsExclusive(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GroupUpdate) SetStatus(v string) *GroupUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableStatus(v *string) *GroupUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSchedulerType sets the "scheduler_type" field.
func (_u *GroupUpdate) SetSchedulerType(v string) *GroupUpdate {
	_u.mutation.SetSchedulerType(v)
	return _u
}

// SetNillableSchedulerType sets the "scheduler_type" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableSchedulerType(v *string) *GroupUpdate {
	if v != nil {
		_u.SetSchedulerType(*v)
	}
	return _u
}

// SetAdvancedSchedulerOverrides sets the "advanced_scheduler_overrides" field.
func (_u *GroupUpdate) SetAdvancedSchedulerOverrides(v policy.GroupAdvancedSchedulerOverrides) *GroupUpdate {
	_u.mutation.SetAdvancedSchedulerOverrides(v)
	return _u
}

// SetNillableAdvancedSchedulerOverrides sets the "advanced_scheduler_overrides" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAdvancedSchedulerOverrides(v *policy.GroupAdvancedSchedulerOverrides) *GroupUpdate {
	if v != nil {
		_u.SetAdvancedSchedulerOverrides(*v)
	}
	return _u
}

// SetDisplayBrand sets the "display_brand" field.
func (_u *GroupUpdate) SetDisplayBrand(v string) *GroupUpdate {
	_u.mutation.SetDisplayBrand(v)
	return _u
}

// SetNillableDisplayBrand sets the "display_brand" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableDisplayBrand(v *string) *GroupUpdate {
	if v != nil {
		_u.SetDisplayBrand(*v)
	}
	return _u
}

// SetAllowImageGeneration sets the "allow_image_generation" field.
func (_u *GroupUpdate) SetAllowImageGeneration(v bool) *GroupUpdate {
	_u.mutation.SetAllowImageGeneration(v)
	return _u
}

// SetNillableAllowImageGeneration sets the "allow_image_generation" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAllowImageGeneration(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetAllowImageGeneration(*v)
	}
	return _u
}

// SetAllowBatchImageGeneration sets the "allow_batch_image_generation" field.
func (_u *GroupUpdate) SetAllowBatchImageGeneration(v bool) *GroupUpdate {
	_u.mutation.SetAllowBatchImageGeneration(v)
	return _u
}

// SetNillableAllowBatchImageGeneration sets the "allow_batch_image_generation" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAllowBatchImageGeneration(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetAllowBatchImageGeneration(*v)
	}
	return _u
}

// SetRoutingPolicy sets the "routing_policy" field.
func (_u *GroupUpdate) SetRoutingPolicy(v jsontext.Value) *GroupUpdate {
	_u.mutation.SetRoutingPolicy(v)
	return _u
}

// AppendRoutingPolicy appends value to the "routing_policy" field.
func (_u *GroupUpdate) AppendRoutingPolicy(v jsontext.Value) *GroupUpdate {
	_u.mutation.AppendRoutingPolicy(v)
	return _u
}

// ClearRoutingPolicy clears the value of the "routing_policy" field.
func (_u *GroupUpdate) ClearRoutingPolicy() *GroupUpdate {
	_u.mutation.ClearRoutingPolicy()
	return _u
}

// SetClaudeCodeOnly sets the "claude_code_only" field.
func (_u *GroupUpdate) SetClaudeCodeOnly(v bool) *GroupUpdate {
	_u.mutation.SetClaudeCodeOnly(v)
	return _u
}

// SetNillableClaudeCodeOnly sets the "claude_code_only" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableClaudeCodeOnly(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetClaudeCodeOnly(*v)
	}
	return _u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_u *GroupUpdate) SetFallbackGroupID(v int64) *GroupUpdate {
	_u.mutation.ResetFallbackGroupID()
	_u.mutation.SetFallbackGroupID(v)
	return _u
}

// SetNillableFallbackGroupID sets the "fallback_group_id" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableFallbackGroupID(v *int64) *GroupUpdate {
	if v != nil {
		_u.SetFallbackGroupID(*v)
	}
	return _u
}

// AddFallbackGroupID adds value to the "fallback_group_id" field.
func (_u *GroupUpdate) AddFallbackGroupID(v int64) *GroupUpdate {
	_u.mutation.AddFallbackGroupID(v)
	return _u
}

// ClearFallbackGroupID clears the value of the "fallback_group_id" field.
func (_u *GroupUpdate) ClearFallbackGroupID() *GroupUpdate {
	_u.mutation.ClearFallbackGroupID()
	return _u
}

// SetFallbackGroupIDOnInvalidRequest sets the "fallback_group_id_on_invalid_request" field.
func (_u *GroupUpdate) SetFallbackGroupIDOnInvalidRequest(v int64) *GroupUpdate {
	_u.mutation.ResetFallbackGroupIDOnInvalidRequest()
	_u.mutation.SetFallbackGroupIDOnInvalidRequest(v)
	return _u
}

// SetNillableFallbackGroupIDOnInvalidRequest sets the "fallback_group_id_on_invalid_request" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableFallbackGroupIDOnInvalidRequest(v *int64) *GroupUpdate {
	if v != nil {
		_u.SetFallbackGroupIDOnInvalidRequest(*v)
	}
	return _u
}

// AddFallbackGroupIDOnInvalidRequest adds value to the "fallback_group_id_on_invalid_request" field.
func (_u *GroupUpdate) AddFallbackGroupIDOnInvalidRequest(v int64) *GroupUpdate {
	_u.mutation.AddFallbackGroupIDOnInvalidRequest(v)
	return _u
}

// ClearFallbackGroupIDOnInvalidRequest clears the value of the "fallback_group_id_on_invalid_request" field.
func (_u *GroupUpdate) ClearFallbackGroupIDOnInvalidRequest() *GroupUpdate {
	_u.mutation.ClearFallbackGroupIDOnInvalidRequest()
	return _u
}

// SetUnavailableFallbackGroupID sets the "unavailable_fallback_group_id" field.
func (_u *GroupUpdate) SetUnavailableFallbackGroupID(v int64) *GroupUpdate {
	_u.mutation.ResetUnavailableFallbackGroupID()
	_u.mutation.SetUnavailableFallbackGroupID(v)
	return _u
}

// SetNillableUnavailableFallbackGroupID sets the "unavailable_fallback_group_id" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableUnavailableFallbackGroupID(v *int64) *GroupUpdate {
	if v != nil {
		_u.SetUnavailableFallbackGroupID(*v)
	}
	return _u
}

// AddUnavailableFallbackGroupID adds value to the "unavailable_fallback_group_id" field.
func (_u *GroupUpdate) AddUnavailableFallbackGroupID(v int64) *GroupUpdate {
	_u.mutation.AddUnavailableFallbackGroupID(v)
	return _u
}

// ClearUnavailableFallbackGroupID clears the value of the "unavailable_fallback_group_id" field.
func (_u *GroupUpdate) ClearUnavailableFallbackGroupID() *GroupUpdate {
	_u.mutation.ClearUnavailableFallbackGroupID()
	return _u
}

// SetModelRouting sets the "model_routing" field.
func (_u *GroupUpdate) SetModelRouting(v map[string][]int64) *GroupUpdate {
	_u.mutation.SetModelRouting(v)
	return _u
}

// ClearModelRouting clears the value of the "model_routing" field.
func (_u *GroupUpdate) ClearModelRouting() *GroupUpdate {
	_u.mutation.ClearModelRouting()
	return _u
}

// SetModelRoutingEnabled sets the "model_routing_enabled" field.
func (_u *GroupUpdate) SetModelRoutingEnabled(v bool) *GroupUpdate {
	_u.mutation.SetModelRoutingEnabled(v)
	return _u
}

// SetNillableModelRoutingEnabled sets the "model_routing_enabled" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableModelRoutingEnabled(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetModelRoutingEnabled(*v)
	}
	return _u
}

// SetMcpXMLInject sets the "mcp_xml_inject" field.
func (_u *GroupUpdate) SetMcpXMLInject(v bool) *GroupUpdate {
	_u.mutation.SetMcpXMLInject(v)
	return _u
}

// SetNillableMcpXMLInject sets the "mcp_xml_inject" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableMcpXMLInject(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetMcpXMLInject(*v)
	}
	return _u
}

// SetSupportedModelScopes sets the "supported_model_scopes" field.
func (_u *GroupUpdate) SetSupportedModelScopes(v []string) *GroupUpdate {
	_u.mutation.SetSupportedModelScopes(v)
	return _u
}

// AppendSupportedModelScopes appends value to the "supported_model_scopes" field.
func (_u *GroupUpdate) AppendSupportedModelScopes(v []string) *GroupUpdate {
	_u.mutation.AppendSupportedModelScopes(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *GroupUpdate) SetSortOrder(v int) *GroupUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableSortOrder(v *int) *GroupUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *GroupUpdate) AddSortOrder(v int) *GroupUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetAllowMessagesDispatch sets the "allow_messages_dispatch" field.
func (_u *GroupUpdate) SetAllowMessagesDispatch(v bool) *GroupUpdate {
	_u.mutation.SetAllowMessagesDispatch(v)
	return _u
}

// SetNillableAllowMessagesDispatch sets the "allow_messages_dispatch" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAllowMessagesDispatch(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetAllowMessagesDispatch(*v)
	}
	return _u
}

// SetAllowedProtocols sets the "allowed_protocols" field.
func (_u *GroupUpdate) SetAllowedProtocols(v []protocol.ProtocolID) *GroupUpdate {
	_u.mutation.SetAllowedProtocols(v)
	return _u
}

// AppendAllowedProtocols appends value to the "allowed_protocols" field.
func (_u *GroupUpdate) AppendAllowedProtocols(v []protocol.ProtocolID) *GroupUpdate {
	_u.mutation.AppendAllowedProtocols(v)
	return _u
}

// SetProtocolFallbacks sets the "protocol_fallbacks" field.
func (_u *GroupUpdate) SetProtocolFallbacks(v map[protocol.ProtocolID][]protocol.ProtocolID) *GroupUpdate {
	_u.mutation.SetProtocolFallbacks(v)
	return _u
}

// SetResponsesImagePolicy sets the "responses_image_policy" field.
func (_u *GroupUpdate) SetResponsesImagePolicy(v string) *GroupUpdate {
	_u.mutation.SetResponsesImagePolicy(v)
	return _u
}

// SetNillableResponsesImagePolicy sets the "responses_image_policy" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableResponsesImagePolicy(v *string) *GroupUpdate {
	if v != nil {
		_u.SetResponsesImagePolicy(*v)
	}
	return _u
}

// SetAllowLive sets the "allow_live" field.
func (_u *GroupUpdate) SetAllowLive(v bool) *GroupUpdate {
	_u.mutation.SetAllowLive(v)
	return _u
}

// SetNillableAllowLive sets the "allow_live" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAllowLive(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetAllowLive(*v)
	}
	return _u
}

// SetOpenaiFastPolicy sets the "openai_fast_policy" field.
func (_u *GroupUpdate) SetOpenaiFastPolicy(v string) *GroupUpdate {
	_u.mutation.SetOpenaiFastPolicy(v)
	return _u
}

// SetNillableOpenaiFastPolicy sets the "openai_fast_policy" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableOpenaiFastPolicy(v *string) *GroupUpdate {
	if v != nil {
		_u.SetOpenaiFastPolicy(*v)
	}
	return _u
}

// SetForceOpenaiFast sets the "force_openai_fast" field.
func (_u *GroupUpdate) SetForceOpenaiFast(v bool) *GroupUpdate {
	_u.mutation.SetForceOpenaiFast(v)
	return _u
}

// SetNillableForceOpenaiFast sets the "force_openai_fast" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableForceOpenaiFast(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetForceOpenaiFast(*v)
	}
	return _u
}

// SetRequireOauthOnly sets the "require_oauth_only" field.
func (_u *GroupUpdate) SetRequireOauthOnly(v bool) *GroupUpdate {
	_u.mutation.SetRequireOauthOnly(v)
	return _u
}

// SetNillableRequireOauthOnly sets the "require_oauth_only" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableRequireOauthOnly(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetRequireOauthOnly(*v)
	}
	return _u
}

// SetRequirePrivacySet sets the "require_privacy_set" field.
func (_u *GroupUpdate) SetRequirePrivacySet(v bool) *GroupUpdate {
	_u.mutation.SetRequirePrivacySet(v)
	return _u
}

// SetNillableRequirePrivacySet sets the "require_privacy_set" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableRequirePrivacySet(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetRequirePrivacySet(*v)
	}
	return _u
}

// SetDefaultMappedModel sets the "default_mapped_model" field.
func (_u *GroupUpdate) SetDefaultMappedModel(v string) *GroupUpdate {
	_u.mutation.SetDefaultMappedModel(v)
	return _u
}

// SetNillableDefaultMappedModel sets the "default_mapped_model" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableDefaultMappedModel(v *string) *GroupUpdate {
	if v != nil {
		_u.SetDefaultMappedModel(*v)
	}
	return _u
}

// SetModelsListConfig sets the "models_list_config" field.
func (_u *GroupUpdate) SetModelsListConfig(v accessview.GroupModelsListConfig) *GroupUpdate {
	_u.mutation.SetModelsListConfig(v)
	return _u
}

// SetNillableModelsListConfig sets the "models_list_config" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableModelsListConfig(v *accessview.GroupModelsListConfig) *GroupUpdate {
	if v != nil {
		_u.SetModelsListConfig(*v)
	}
	return _u
}

// SetAvailabilityProbeConfig sets the "availability_probe_config" field.
func (_u *GroupUpdate) SetAvailabilityProbeConfig(v accessview.GroupAvailabilityProbeConfig) *GroupUpdate {
	_u.mutation.SetAvailabilityProbeConfig(v)
	return _u
}

// SetNillableAvailabilityProbeConfig sets the "availability_probe_config" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAvailabilityProbeConfig(v *accessview.GroupAvailabilityProbeConfig) *GroupUpdate {
	if v != nil {
		_u.SetAvailabilityProbeConfig(*v)
	}
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *GroupUpdate) SetRpmLimit(v int) *GroupUpdate {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableRpmLimit(v *int) *GroupUpdate {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *GroupUpdate) AddRpmLimit(v int) *GroupUpdate {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetMaxReasoningEffort sets the "max_reasoning_effort" field.
func (_u *GroupUpdate) SetMaxReasoningEffort(v string) *GroupUpdate {
	_u.mutation.SetMaxReasoningEffort(v)
	return _u
}

// SetNillableMaxReasoningEffort sets the "max_reasoning_effort" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableMaxReasoningEffort(v *string) *GroupUpdate {
	if v != nil {
		_u.SetMaxReasoningEffort(*v)
	}
	return _u
}

// SetMaxReasoningEffortOverLimit sets the "max_reasoning_effort_over_limit" field.
func (_u *GroupUpdate) SetMaxReasoningEffortOverLimit(v string) *GroupUpdate {
	_u.mutation.SetMaxReasoningEffortOverLimit(v)
	return _u
}

// SetNillableMaxReasoningEffortOverLimit sets the "max_reasoning_effort_over_limit" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableMaxReasoningEffortOverLimit(v *string) *GroupUpdate {
	if v != nil {
		_u.SetMaxReasoningEffortOverLimit(*v)
	}
	return _u
}

// SetReasoningEffortMappings sets the "reasoning_effort_mappings" field.
func (_u *GroupUpdate) SetReasoningEffortMappings(v []accessview.ReasoningEffortMapping) *GroupUpdate {
	_u.mutation.SetReasoningEffortMappings(v)
	return _u
}

// AppendReasoningEffortMappings appends value to the "reasoning_effort_mappings" field.
func (_u *GroupUpdate) AppendReasoningEffortMappings(v []accessview.ReasoningEffortMapping) *GroupUpdate {
	_u.mutation.AppendReasoningEffortMappings(v)
	return _u
}

// SetSessionIsolationEnabled sets the "session_isolation_enabled" field.
func (_u *GroupUpdate) SetSessionIsolationEnabled(v bool) *GroupUpdate {
	_u.mutation.SetSessionIsolationEnabled(v)
	return _u
}

// SetNillableSessionIsolationEnabled sets the "session_isolation_enabled" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableSessionIsolationEnabled(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetSessionIsolationEnabled(*v)
	}
	return _u
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *GroupUpdate) AddAPIKeyIDs(ids ...int64) *GroupUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *GroupUpdate) AddAPIKeys(v ...*APIKey) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddAPIKeyCompositeGroupIDs adds the "api_key_composite_groups" edge to the APIKeyCompositeGroup entity by IDs.
func (_u *GroupUpdate) AddAPIKeyCompositeGroupIDs(ids ...int64) *GroupUpdate {
	_u.mutation.AddAPIKeyCompositeGroupIDs(ids...)
	return _u
}

// AddAPIKeyCompositeGroups adds the "api_key_composite_groups" edges to the APIKeyCompositeGroup entity.
func (_u *GroupUpdate) AddAPIKeyCompositeGroups(v ...*APIKeyCompositeGroup) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyCompositeGroupIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *GroupUpdate) AddUsageLogIDs(ids ...int64) *GroupUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *GroupUpdate) AddUsageLogs(v ...*UsageLog) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// AddProviderIDs adds the "providers" edge to the Provider entity by IDs.
func (_u *GroupUpdate) AddProviderIDs(ids ...int64) *GroupUpdate {
	_u.mutation.AddProviderIDs(ids...)
	return _u
}

// AddProviders adds the "providers" edges to the Provider entity.
func (_u *GroupUpdate) AddProviders(v ...*Provider) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProviderIDs(ids...)
}

// AddAllowedUserIDs adds the "allowed_users" edge to the User entity by IDs.
func (_u *GroupUpdate) AddAllowedUserIDs(ids ...int64) *GroupUpdate {
	_u.mutation.AddAllowedUserIDs(ids...)
	return _u
}

// AddAllowedUsers adds the "allowed_users" edges to the User entity.
func (_u *GroupUpdate) AddAllowedUsers(v ...*User) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllowedUserIDs(ids...)
}

// AddDisabledPublicUserIDs adds the "disabled_public_users" edge to the User entity by IDs.
func (_u *GroupUpdate) AddDisabledPublicUserIDs(ids ...int64) *GroupUpdate {
	_u.mutation.AddDisabledPublicUserIDs(ids...)
	return _u
}

// AddDisabledPublicUsers adds the "disabled_public_users" edges to the User entity.
func (_u *GroupUpdate) AddDisabledPublicUsers(v ...*User) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDisabledPublicUserIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdate) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *GroupUpdate) ClearAPIKeys() *GroupUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *GroupUpdate) RemoveAPIKeyIDs(ids ...int64) *GroupUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *GroupUpdate) RemoveAPIKeys(v ...*APIKey) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearAPIKeyCompositeGroups clears all "api_key_composite_groups" edges to the APIKeyCompositeGroup entity.
func (_u *GroupUpdate) ClearAPIKeyCompositeGroups() *GroupUpdate {
	_u.mutation.ClearAPIKeyCompositeGroups()
	return _u
}

// RemoveAPIKeyCompositeGroupIDs removes the "api_key_composite_groups" edge to APIKeyCompositeGroup entities by IDs.
func (_u *GroupUpdate) RemoveAPIKeyCompositeGroupIDs(ids ...int64) *GroupUpdate {
	_u.mutation.RemoveAPIKeyCompositeGroupIDs(ids...)
	return _u
}

// RemoveAPIKeyCompositeGroups removes "api_key_composite_groups" edges to APIKeyCompositeGroup entities.
func (_u *GroupUpdate) RemoveAPIKeyCompositeGroups(v ...*APIKeyCompositeGroup) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyCompositeGroupIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *GroupUpdate) ClearUsageLogs() *GroupUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *GroupUpdate) RemoveUsageLogIDs(ids ...int64) *GroupUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *GroupUpdate) RemoveUsageLogs(v ...*UsageLog) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// ClearProviders clears all "providers" edges to the Provider entity.
func (_u *GroupUpdate) ClearProviders() *GroupUpdate {
	_u.mutation.ClearProviders()
	return _u
}

// RemoveProviderIDs removes the "providers" edge to Provider entities by IDs.
func (_u *GroupUpdate) RemoveProviderIDs(ids ...int64) *GroupUpdate {
	_u.mutation.RemoveProviderIDs(ids...)
	return _u
}

// RemoveProviders removes "providers" edges to Provider entities.
func (_u *GroupUpdate) RemoveProviders(v ...*Provider) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProviderIDs(ids...)
}

// ClearAllowedUsers clears all "allowed_users" edges to the User entity.
func (_u *GroupUpdate) ClearAllowedUsers() *GroupUpdate {
	_u.mutation.ClearAllowedUsers()
	return _u
}

// RemoveAllowedUserIDs removes the "allowed_users" edge to User entities by IDs.
func (_u *GroupUpdate) RemoveAllowedUserIDs(ids ...int64) *GroupUpdate {
	_u.mutation.RemoveAllowedUserIDs(ids...)
	return _u
}

// RemoveAllowedUsers removes "allowed_users" edges to User entities.
func (_u *GroupUpdate) RemoveAllowedUsers(v ...*User) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllowedUserIDs(ids...)
}

// ClearDisabledPublicUsers clears all "disabled_public_users" edges to the User entity.
func (_u *GroupUpdate) ClearDisabledPublicUsers() *GroupUpdate {
	_u.mutation.ClearDisabledPublicUsers()
	return _u
}

// RemoveDisabledPublicUserIDs removes the "disabled_public_users" edge to User entities by IDs.
func (_u *GroupUpdate) RemoveDisabledPublicUserIDs(ids ...int64) *GroupUpdate {
	_u.mutation.RemoveDisabledPublicUserIDs(ids...)
	return _u
}

// RemoveDisabledPublicUsers removes "disabled_public_users" edges to User entities.
func (_u *GroupUpdate) RemoveDisabledPublicUsers(v ...*User) *GroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDisabledPublicUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if group.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized group.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := group.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := group.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Group.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SchedulerType(); ok {
		if err := group.SchedulerTypeValidator(v); err != nil {
			return &ValidationError{Name: "scheduler_type", err: fmt.Errorf(`ent: validator failed for field "Group.scheduler_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayBrand(); ok {
		if err := group.DisplayBrandValidator(v); err != nil {
			return &ValidationError{Name: "display_brand", err: fmt.Errorf(`ent: validator failed for field "Group.display_brand": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultMappedModel(); ok {
		if err := group.DefaultMappedModelValidator(v); err != nil {
			return &ValidationError{Name: "default_mapped_model", err: fmt.Errorf(`ent: validator failed for field "Group.default_mapped_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxReasoningEffort(); ok {
		if err := group.MaxReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "max_reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "Group.max_reasoning_effort": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxReasoningEffortOverLimit(); ok {
		if err := group.MaxReasoningEffortOverLimitValidator(v); err != nil {
			return &ValidationError{Name: "max_reasoning_effort_over_limit", err: fmt.Errorf(`ent: validator failed for field "Group.max_reasoning_effort_over_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(group.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(group.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Localization(); ok {
		_spec.SetField(group.FieldLocalization, field.TypeJSON, value)
	}
	if _u.mutation.LocalizationCleared() {
		_spec.ClearField(group.FieldLocalization, field.TypeJSON)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(group.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(group.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsExclusive(); ok {
		_spec.SetField(group.FieldIsExclusive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(group.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.DuplicateOperationIDCleared() {
		_spec.ClearField(group.FieldDuplicateOperationID, field.TypeString)
	}
	if value, ok := _u.mutation.SchedulerType(); ok {
		_spec.SetField(group.FieldSchedulerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdvancedSchedulerOverrides(); ok {
		_spec.SetField(group.FieldAdvancedSchedulerOverrides, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DisplayBrand(); ok {
		_spec.SetField(group.FieldDisplayBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowImageGeneration(); ok {
		_spec.SetField(group.FieldAllowImageGeneration, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowBatchImageGeneration(); ok {
		_spec.SetField(group.FieldAllowBatchImageGeneration, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RoutingPolicy(); ok {
		_spec.SetField(group.FieldRoutingPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoutingPolicy(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldRoutingPolicy, value)
		})
	}
	if _u.mutation.RoutingPolicyCleared() {
		_spec.ClearField(group.FieldRoutingPolicy, field.TypeJSON)
	}
	if value, ok := _u.mutation.ClaudeCodeOnly(); ok {
		_spec.SetField(group.FieldClaudeCodeOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FallbackGroupID(); ok {
		_spec.SetField(group.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupID(); ok {
		_spec.AddField(group.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if _u.mutation.FallbackGroupIDCleared() {
		_spec.ClearField(group.FieldFallbackGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FallbackGroupIDOnInvalidRequest(); ok {
		_spec.SetField(group.FieldFallbackGroupIDOnInvalidRequest, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupIDOnInvalidRequest(); ok {
		_spec.AddField(group.FieldFallbackGroupIDOnInvalidRequest, field.TypeInt64, value)
	}
	if _u.mutation.FallbackGroupIDOnInvalidRequestCleared() {
		_spec.ClearField(group.FieldFallbackGroupIDOnInvalidRequest, field.TypeInt64)
	}
	if value, ok := _u.mutation.UnavailableFallbackGroupID(); ok {
		_spec.SetField(group.FieldUnavailableFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnavailableFallbackGroupID(); ok {
		_spec.AddField(group.FieldUnavailableFallbackGroupID, field.TypeInt64, value)
	}
	if _u.mutation.UnavailableFallbackGroupIDCleared() {
		_spec.ClearField(group.FieldUnavailableFallbackGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ModelRouting(); ok {
		_spec.SetField(group.FieldModelRouting, field.TypeJSON, value)
	}
	if _u.mutation.ModelRoutingCleared() {
		_spec.ClearField(group.FieldModelRouting, field.TypeJSON)
	}
	if value, ok := _u.mutation.ModelRoutingEnabled(); ok {
		_spec.SetField(group.FieldModelRoutingEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.McpXMLInject(); ok {
		_spec.SetField(group.FieldMcpXMLInject, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportedModelScopes(); ok {
		_spec.SetField(group.FieldSupportedModelScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedModelScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldSupportedModelScopes, value)
		})
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(group.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(group.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowMessagesDispatch(); ok {
		_spec.SetField(group.FieldAllowMessagesDispatch, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowedProtocols(); ok {
		_spec.SetField(group.FieldAllowedProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldAllowedProtocols, value)
		})
	}
	if value, ok := _u.mutation.ProtocolFallbacks(); ok {
		_spec.SetField(group.FieldProtocolFallbacks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ResponsesImagePolicy(); ok {
		_spec.SetField(group.FieldResponsesImagePolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowLive(); ok {
		_spec.SetField(group.FieldAllowLive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OpenaiFastPolicy(); ok {
		_spec.SetField(group.FieldOpenaiFastPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForceOpenaiFast(); ok {
		_spec.SetField(group.FieldForceOpenaiFast, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireOauthOnly(); ok {
		_spec.SetField(group.FieldRequireOauthOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequirePrivacySet(); ok {
		_spec.SetField(group.FieldRequirePrivacySet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultMappedModel(); ok {
		_spec.SetField(group.FieldDefaultMappedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelsListConfig(); ok {
		_spec.SetField(group.FieldModelsListConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AvailabilityProbeConfig(); ok {
		_spec.SetField(group.FieldAvailabilityProbeConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(group.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(group.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxReasoningEffort(); ok {
		_spec.SetField(group.FieldMaxReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxReasoningEffortOverLimit(); ok {
		_spec.SetField(group.FieldMaxReasoningEffortOverLimit, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffortMappings(); ok {
		_spec.SetField(group.FieldReasoningEffortMappings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReasoningEffortMappings(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldReasoningEffortMappings, value)
		})
	}
	if value, ok := _u.mutation.SessionIsolationEnabled(); ok {
		_spec.SetField(group.FieldSessionIsolationEnabled, field.TypeBool, value)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeysTable,
			Columns: []string{group.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeysTable,
			Columns: []string{group.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeysTable,
			Columns: []string{group.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCompositeGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeyCompositeGroupsTable,
			Columns: []string{group.APIKeyCompositeGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeyCompositeGroupsIDs(); len(nodes) > 0 && !_u.mutation.APIKeyCompositeGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeyCompositeGroupsTable,
			Columns: []string{group.APIKeyCompositeGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyCompositeGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeyCompositeGroupsTable,
			Columns: []string{group.APIKeyCompositeGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsageLogsTable,
			Columns: []string{group.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsageLogsTable,
			Columns: []string{group.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsageLogsTable,
			Columns: []string{group.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.ProvidersTable,
			Columns: group.ProvidersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProvidersIDs(); len(nodes) > 0 && !_u.mutation.ProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.ProvidersTable,
			Columns: group.ProvidersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.ProvidersTable,
			Columns: group.ProvidersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllowedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AllowedUsersTable,
			Columns: group.AllowedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &UserAllowedGroupCreate{config: _u.config, mutation: newUserAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllowedUsersIDs(); len(nodes) > 0 && !_u.mutation.AllowedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AllowedUsersTable,
			Columns: group.AllowedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserAllowedGroupCreate{config: _u.config, mutation: newUserAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllowedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AllowedUsersTable,
			Columns: group.AllowedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserAllowedGroupCreate{config: _u.config, mutation: newUserAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DisabledPublicUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.DisabledPublicUsersTable,
			Columns: group.DisabledPublicUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &UserDisabledPublicGroupCreate{config: _u.config, mutation: newUserDisabledPublicGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDisabledPublicUsersIDs(); len(nodes) > 0 && !_u.mutation.DisabledPublicUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.DisabledPublicUsersTable,
			Columns: group.DisabledPublicUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserDisabledPublicGroupCreate{config: _u.config, mutation: newUserDisabledPublicGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DisabledPublicUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.DisabledPublicUsersTable,
			Columns: group.DisabledPublicUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserDisabledPublicGroupCreate{config: _u.config, mutation: newUserDisabledPublicGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupUpdateOne) SetUpdatedAt(v time.Time) *GroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GroupUpdateOne) SetDeletedAt(v time.Time) *GroupUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableDeletedAt(v *time.Time) *GroupUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GroupUpdateOne) ClearDeletedAt() *GroupUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetLocalization sets the "localization" field.
func (_u *GroupUpdateOne) SetLocalization(v accessview.GroupLocalization) *GroupUpdateOne {
	_u.mutation.SetLocalization(v)
	return _u
}

// SetNillableLocalization sets the "localization" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableLocalization(v *accessview.GroupLocalization) *GroupUpdateOne {
	if v != nil {
		_u.SetLocalization(*v)
	}
	return _u
}

// ClearLocalization clears the value of the "localization" field.
func (_u *GroupUpdateOne) ClearLocalization() *GroupUpdateOne {
	_u.mutation.ClearLocalization()
	return _u
}

// SetName sets the "name" field.
func (_u *GroupUpdateOne) SetName(v string) *GroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableName(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupUpdateOne) SetDescription(v string) *GroupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableDescription(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupUpdateOne) ClearDescription() *GroupUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *GroupUpdateOne) SetRateMultiplier(v float64) *GroupUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableRateMultiplier(v *float64) *GroupUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *GroupUpdateOne) AddRateMultiplier(v float64) *GroupUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetIsExclusive sets the "is_exclusive" field.
func (_u *GroupUpdateOne) SetIsExclusive(v bool) *GroupUpdateOne {
	_u.mutation.SetIsExclusive(v)
	return _u
}

// SetNillableIsExclusive sets the "is_exclusive" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableIsExclusive(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetIsExclusive(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GroupUpdateOne) SetStatus(v string) *GroupUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableStatus(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSchedulerType sets the "scheduler_type" field.
func (_u *GroupUpdateOne) SetSchedulerType(v string) *GroupUpdateOne {
	_u.mutation.SetSchedulerType(v)
	return _u
}

// SetNillableSchedulerType sets the "scheduler_type" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableSchedulerType(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetSchedulerType(*v)
	}
	return _u
}

// SetAdvancedSchedulerOverrides sets the "advanced_scheduler_overrides" field.
func (_u *GroupUpdateOne) SetAdvancedSchedulerOverrides(v policy.GroupAdvancedSchedulerOverrides) *GroupUpdateOne {
	_u.mutation.SetAdvancedSchedulerOverrides(v)
	return _u
}

// SetNillableAdvancedSchedulerOverrides sets the "advanced_scheduler_overrides" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAdvancedSchedulerOverrides(v *policy.GroupAdvancedSchedulerOverrides) *GroupUpdateOne {
	if v != nil {
		_u.SetAdvancedSchedulerOverrides(*v)
	}
	return _u
}

// SetDisplayBrand sets the "display_brand" field.
func (_u *GroupUpdateOne) SetDisplayBrand(v string) *GroupUpdateOne {
	_u.mutation.SetDisplayBrand(v)
	return _u
}

// SetNillableDisplayBrand sets the "display_brand" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableDisplayBrand(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetDisplayBrand(*v)
	}
	return _u
}

// SetAllowImageGeneration sets the "allow_image_generation" field.
func (_u *GroupUpdateOne) SetAllowImageGeneration(v bool) *GroupUpdateOne {
	_u.mutation.SetAllowImageGeneration(v)
	return _u
}

// SetNillableAllowImageGeneration sets the "allow_image_generation" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAllowImageGeneration(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetAllowImageGeneration(*v)
	}
	return _u
}

// SetAllowBatchImageGeneration sets the "allow_batch_image_generation" field.
func (_u *GroupUpdateOne) SetAllowBatchImageGeneration(v bool) *GroupUpdateOne {
	_u.mutation.SetAllowBatchImageGeneration(v)
	return _u
}

// SetNillableAllowBatchImageGeneration sets the "allow_batch_image_generation" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAllowBatchImageGeneration(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetAllowBatchImageGeneration(*v)
	}
	return _u
}

// SetRoutingPolicy sets the "routing_policy" field.
func (_u *GroupUpdateOne) SetRoutingPolicy(v jsontext.Value) *GroupUpdateOne {
	_u.mutation.SetRoutingPolicy(v)
	return _u
}

// AppendRoutingPolicy appends value to the "routing_policy" field.
func (_u *GroupUpdateOne) AppendRoutingPolicy(v jsontext.Value) *GroupUpdateOne {
	_u.mutation.AppendRoutingPolicy(v)
	return _u
}

// ClearRoutingPolicy clears the value of the "routing_policy" field.
func (_u *GroupUpdateOne) ClearRoutingPolicy() *GroupUpdateOne {
	_u.mutation.ClearRoutingPolicy()
	return _u
}

// SetClaudeCodeOnly sets the "claude_code_only" field.
func (_u *GroupUpdateOne) SetClaudeCodeOnly(v bool) *GroupUpdateOne {
	_u.mutation.SetClaudeCodeOnly(v)
	return _u
}

// SetNillableClaudeCodeOnly sets the "claude_code_only" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableClaudeCodeOnly(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetClaudeCodeOnly(*v)
	}
	return _u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_u *GroupUpdateOne) SetFallbackGroupID(v int64) *GroupUpdateOne {
	_u.mutation.ResetFallbackGroupID()
	_u.mutation.SetFallbackGroupID(v)
	return _u
}

// SetNillableFallbackGroupID sets the "fallback_group_id" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableFallbackGroupID(v *int64) *GroupUpdateOne {
	if v != nil {
		_u.SetFallbackGroupID(*v)
	}
	return _u
}

// AddFallbackGroupID adds value to the "fallback_group_id" field.
func (_u *GroupUpdateOne) AddFallbackGroupID(v int64) *GroupUpdateOne {
	_u.mutation.AddFallbackGroupID(v)
	return _u
}

// ClearFallbackGroupID clears the value of the "fallback_group_id" field.
func (_u *GroupUpdateOne) ClearFallbackGroupID() *GroupUpdateOne {
	_u.mutation.ClearFallbackGroupID()
	return _u
}

// SetFallbackGroupIDOnInvalidRequest sets the "fallback_group_id_on_invalid_request" field.
func (_u *GroupUpdateOne) SetFallbackGroupIDOnInvalidRequest(v int64) *GroupUpdateOne {
	_u.mutation.ResetFallbackGroupIDOnInvalidRequest()
	_u.mutation.SetFallbackGroupIDOnInvalidRequest(v)
	return _u
}

// SetNillableFallbackGroupIDOnInvalidRequest sets the "fallback_group_id_on_invalid_request" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableFallbackGroupIDOnInvalidRequest(v *int64) *GroupUpdateOne {
	if v != nil {
		_u.SetFallbackGroupIDOnInvalidRequest(*v)
	}
	return _u
}

// AddFallbackGroupIDOnInvalidRequest adds value to the "fallback_group_id_on_invalid_request" field.
func (_u *GroupUpdateOne) AddFallbackGroupIDOnInvalidRequest(v int64) *GroupUpdateOne {
	_u.mutation.AddFallbackGroupIDOnInvalidRequest(v)
	return _u
}

// ClearFallbackGroupIDOnInvalidRequest clears the value of the "fallback_group_id_on_invalid_request" field.
func (_u *GroupUpdateOne) ClearFallbackGroupIDOnInvalidRequest() *GroupUpdateOne {
	_u.mutation.ClearFallbackGroupIDOnInvalidRequest()
	return _u
}

// SetUnavailableFallbackGroupID sets the "unavailable_fallback_group_id" field.
func (_u *GroupUpdateOne) SetUnavailableFallbackGroupID(v int64) *GroupUpdateOne {
	_u.mutation.ResetUnavailableFallbackGroupID()
	_u.mutation.SetUnavailableFallbackGroupID(v)
	return _u
}

// SetNillableUnavailableFallbackGroupID sets the "unavailable_fallback_group_id" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableUnavailableFallbackGroupID(v *int64) *GroupUpdateOne {
	if v != nil {
		_u.SetUnavailableFallbackGroupID(*v)
	}
	return _u
}

// AddUnavailableFallbackGroupID adds value to the "unavailable_fallback_group_id" field.
func (_u *GroupUpdateOne) AddUnavailableFallbackGroupID(v int64) *GroupUpdateOne {
	_u.mutation.AddUnavailableFallbackGroupID(v)
	return _u
}

// ClearUnavailableFallbackGroupID clears the value of the "unavailable_fallback_group_id" field.
func (_u *GroupUpdateOne) ClearUnavailableFallbackGroupID() *GroupUpdateOne {
	_u.mutation.ClearUnavailableFallbackGroupID()
	return _u
}

// SetModelRouting sets the "model_routing" field.
func (_u *GroupUpdateOne) SetModelRouting(v map[string][]int64) *GroupUpdateOne {
	_u.mutation.SetModelRouting(v)
	return _u
}

// ClearModelRouting clears the value of the "model_routing" field.
func (_u *GroupUpdateOne) ClearModelRouting() *GroupUpdateOne {
	_u.mutation.ClearModelRouting()
	return _u
}

// SetModelRoutingEnabled sets the "model_routing_enabled" field.
func (_u *GroupUpdateOne) SetModelRoutingEnabled(v bool) *GroupUpdateOne {
	_u.mutation.SetModelRoutingEnabled(v)
	return _u
}

// SetNillableModelRoutingEnabled sets the "model_routing_enabled" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableModelRoutingEnabled(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetModelRoutingEnabled(*v)
	}
	return _u
}

// SetMcpXMLInject sets the "mcp_xml_inject" field.
func (_u *GroupUpdateOne) SetMcpXMLInject(v bool) *GroupUpdateOne {
	_u.mutation.SetMcpXMLInject(v)
	return _u
}

// SetNillableMcpXMLInject sets the "mcp_xml_inject" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableMcpXMLInject(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetMcpXMLInject(*v)
	}
	return _u
}

// SetSupportedModelScopes sets the "supported_model_scopes" field.
func (_u *GroupUpdateOne) SetSupportedModelScopes(v []string) *GroupUpdateOne {
	_u.mutation.SetSupportedModelScopes(v)
	return _u
}

// AppendSupportedModelScopes appends value to the "supported_model_scopes" field.
func (_u *GroupUpdateOne) AppendSupportedModelScopes(v []string) *GroupUpdateOne {
	_u.mutation.AppendSupportedModelScopes(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *GroupUpdateOne) SetSortOrder(v int) *GroupUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableSortOrder(v *int) *GroupUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *GroupUpdateOne) AddSortOrder(v int) *GroupUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetAllowMessagesDispatch sets the "allow_messages_dispatch" field.
func (_u *GroupUpdateOne) SetAllowMessagesDispatch(v bool) *GroupUpdateOne {
	_u.mutation.SetAllowMessagesDispatch(v)
	return _u
}

// SetNillableAllowMessagesDispatch sets the "allow_messages_dispatch" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAllowMessagesDispatch(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetAllowMessagesDispatch(*v)
	}
	return _u
}

// SetAllowedProtocols sets the "allowed_protocols" field.
func (_u *GroupUpdateOne) SetAllowedProtocols(v []protocol.ProtocolID) *GroupUpdateOne {
	_u.mutation.SetAllowedProtocols(v)
	return _u
}

// AppendAllowedProtocols appends value to the "allowed_protocols" field.
func (_u *GroupUpdateOne) AppendAllowedProtocols(v []protocol.ProtocolID) *GroupUpdateOne {
	_u.mutation.AppendAllowedProtocols(v)
	return _u
}

// SetProtocolFallbacks sets the "protocol_fallbacks" field.
func (_u *GroupUpdateOne) SetProtocolFallbacks(v map[protocol.ProtocolID][]protocol.ProtocolID) *GroupUpdateOne {
	_u.mutation.SetProtocolFallbacks(v)
	return _u
}

// SetResponsesImagePolicy sets the "responses_image_policy" field.
func (_u *GroupUpdateOne) SetResponsesImagePolicy(v string) *GroupUpdateOne {
	_u.mutation.SetResponsesImagePolicy(v)
	return _u
}

// SetNillableResponsesImagePolicy sets the "responses_image_policy" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableResponsesImagePolicy(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetResponsesImagePolicy(*v)
	}
	return _u
}

// SetAllowLive sets the "allow_live" field.
func (_u *GroupUpdateOne) SetAllowLive(v bool) *GroupUpdateOne {
	_u.mutation.SetAllowLive(v)
	return _u
}

// SetNillableAllowLive sets the "allow_live" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAllowLive(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetAllowLive(*v)
	}
	return _u
}

// SetOpenaiFastPolicy sets the "openai_fast_policy" field.
func (_u *GroupUpdateOne) SetOpenaiFastPolicy(v string) *GroupUpdateOne {
	_u.mutation.SetOpenaiFastPolicy(v)
	return _u
}

// SetNillableOpenaiFastPolicy sets the "openai_fast_policy" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableOpenaiFastPolicy(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetOpenaiFastPolicy(*v)
	}
	return _u
}

// SetForceOpenaiFast sets the "force_openai_fast" field.
func (_u *GroupUpdateOne) SetForceOpenaiFast(v bool) *GroupUpdateOne {
	_u.mutation.SetForceOpenaiFast(v)
	return _u
}

// SetNillableForceOpenaiFast sets the "force_openai_fast" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableForceOpenaiFast(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetForceOpenaiFast(*v)
	}
	return _u
}

// SetRequireOauthOnly sets the "require_oauth_only" field.
func (_u *GroupUpdateOne) SetRequireOauthOnly(v bool) *GroupUpdateOne {
	_u.mutation.SetRequireOauthOnly(v)
	return _u
}

// SetNillableRequireOauthOnly sets the "require_oauth_only" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableRequireOauthOnly(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetRequireOauthOnly(*v)
	}
	return _u
}

// SetRequirePrivacySet sets the "require_privacy_set" field.
func (_u *GroupUpdateOne) SetRequirePrivacySet(v bool) *GroupUpdateOne {
	_u.mutation.SetRequirePrivacySet(v)
	return _u
}

// SetNillableRequirePrivacySet sets the "require_privacy_set" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableRequirePrivacySet(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetRequirePrivacySet(*v)
	}
	return _u
}

// SetDefaultMappedModel sets the "default_mapped_model" field.
func (_u *GroupUpdateOne) SetDefaultMappedModel(v string) *GroupUpdateOne {
	_u.mutation.SetDefaultMappedModel(v)
	return _u
}

// SetNillableDefaultMappedModel sets the "default_mapped_model" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableDefaultMappedModel(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetDefaultMappedModel(*v)
	}
	return _u
}

// SetModelsListConfig sets the "models_list_config" field.
func (_u *GroupUpdateOne) SetModelsListConfig(v accessview.GroupModelsListConfig) *GroupUpdateOne {
	_u.mutation.SetModelsListConfig(v)
	return _u
}

// SetNillableModelsListConfig sets the "models_list_config" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableModelsListConfig(v *accessview.GroupModelsListConfig) *GroupUpdateOne {
	if v != nil {
		_u.SetModelsListConfig(*v)
	}
	return _u
}

// SetAvailabilityProbeConfig sets the "availability_probe_config" field.
func (_u *GroupUpdateOne) SetAvailabilityProbeConfig(v accessview.GroupAvailabilityProbeConfig) *GroupUpdateOne {
	_u.mutation.SetAvailabilityProbeConfig(v)
	return _u
}

// SetNillableAvailabilityProbeConfig sets the "availability_probe_config" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAvailabilityProbeConfig(v *accessview.GroupAvailabilityProbeConfig) *GroupUpdateOne {
	if v != nil {
		_u.SetAvailabilityProbeConfig(*v)
	}
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *GroupUpdateOne) SetRpmLimit(v int) *GroupUpdateOne {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableRpmLimit(v *int) *GroupUpdateOne {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *GroupUpdateOne) AddRpmLimit(v int) *GroupUpdateOne {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetMaxReasoningEffort sets the "max_reasoning_effort" field.
func (_u *GroupUpdateOne) SetMaxReasoningEffort(v string) *GroupUpdateOne {
	_u.mutation.SetMaxReasoningEffort(v)
	return _u
}

// SetNillableMaxReasoningEffort sets the "max_reasoning_effort" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableMaxReasoningEffort(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetMaxReasoningEffort(*v)
	}
	return _u
}

// SetMaxReasoningEffortOverLimit sets the "max_reasoning_effort_over_limit" field.
func (_u *GroupUpdateOne) SetMaxReasoningEffortOverLimit(v string) *GroupUpdateOne {
	_u.mutation.SetMaxReasoningEffortOverLimit(v)
	return _u
}

// SetNillableMaxReasoningEffortOverLimit sets the "max_reasoning_effort_over_limit" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableMaxReasoningEffortOverLimit(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetMaxReasoningEffortOverLimit(*v)
	}
	return _u
}

// SetReasoningEffortMappings sets the "reasoning_effort_mappings" field.
func (_u *GroupUpdateOne) SetReasoningEffortMappings(v []accessview.ReasoningEffortMapping) *GroupUpdateOne {
	_u.mutation.SetReasoningEffortMappings(v)
	return _u
}

// AppendReasoningEffortMappings appends value to the "reasoning_effort_mappings" field.
func (_u *GroupUpdateOne) AppendReasoningEffortMappings(v []accessview.ReasoningEffortMapping) *GroupUpdateOne {
	_u.mutation.AppendReasoningEffortMappings(v)
	return _u
}

// SetSessionIsolationEnabled sets the "session_isolation_enabled" field.
func (_u *GroupUpdateOne) SetSessionIsolationEnabled(v bool) *GroupUpdateOne {
	_u.mutation.SetSessionIsolationEnabled(v)
	return _u
}

// SetNillableSessionIsolationEnabled sets the "session_isolation_enabled" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableSessionIsolationEnabled(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetSessionIsolationEnabled(*v)
	}
	return _u
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *GroupUpdateOne) AddAPIKeyIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *GroupUpdateOne) AddAPIKeys(v ...*APIKey) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddAPIKeyCompositeGroupIDs adds the "api_key_composite_groups" edge to the APIKeyCompositeGroup entity by IDs.
func (_u *GroupUpdateOne) AddAPIKeyCompositeGroupIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.AddAPIKeyCompositeGroupIDs(ids...)
	return _u
}

// AddAPIKeyCompositeGroups adds the "api_key_composite_groups" edges to the APIKeyCompositeGroup entity.
func (_u *GroupUpdateOne) AddAPIKeyCompositeGroups(v ...*APIKeyCompositeGroup) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyCompositeGroupIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *GroupUpdateOne) AddUsageLogIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *GroupUpdateOne) AddUsageLogs(v ...*UsageLog) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// AddProviderIDs adds the "providers" edge to the Provider entity by IDs.
func (_u *GroupUpdateOne) AddProviderIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.AddProviderIDs(ids...)
	return _u
}

// AddProviders adds the "providers" edges to the Provider entity.
func (_u *GroupUpdateOne) AddProviders(v ...*Provider) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProviderIDs(ids...)
}

// AddAllowedUserIDs adds the "allowed_users" edge to the User entity by IDs.
func (_u *GroupUpdateOne) AddAllowedUserIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.AddAllowedUserIDs(ids...)
	return _u
}

// AddAllowedUsers adds the "allowed_users" edges to the User entity.
func (_u *GroupUpdateOne) AddAllowedUsers(v ...*User) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllowedUserIDs(ids...)
}

// AddDisabledPublicUserIDs adds the "disabled_public_users" edge to the User entity by IDs.
func (_u *GroupUpdateOne) AddDisabledPublicUserIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.AddDisabledPublicUserIDs(ids...)
	return _u
}

// AddDisabledPublicUsers adds the "disabled_public_users" edges to the User entity.
func (_u *GroupUpdateOne) AddDisabledPublicUsers(v ...*User) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDisabledPublicUserIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdateOne) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *GroupUpdateOne) ClearAPIKeys() *GroupUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *GroupUpdateOne) RemoveAPIKeyIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *GroupUpdateOne) RemoveAPIKeys(v ...*APIKey) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearAPIKeyCompositeGroups clears all "api_key_composite_groups" edges to the APIKeyCompositeGroup entity.
func (_u *GroupUpdateOne) ClearAPIKeyCompositeGroups() *GroupUpdateOne {
	_u.mutation.ClearAPIKeyCompositeGroups()
	return _u
}

// RemoveAPIKeyCompositeGroupIDs removes the "api_key_composite_groups" edge to APIKeyCompositeGroup entities by IDs.
func (_u *GroupUpdateOne) RemoveAPIKeyCompositeGroupIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.RemoveAPIKeyCompositeGroupIDs(ids...)
	return _u
}

// RemoveAPIKeyCompositeGroups removes "api_key_composite_groups" edges to APIKeyCompositeGroup entities.
func (_u *GroupUpdateOne) RemoveAPIKeyCompositeGroups(v ...*APIKeyCompositeGroup) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyCompositeGroupIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *GroupUpdateOne) ClearUsageLogs() *GroupUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *GroupUpdateOne) RemoveUsageLogIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *GroupUpdateOne) RemoveUsageLogs(v ...*UsageLog) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// ClearProviders clears all "providers" edges to the Provider entity.
func (_u *GroupUpdateOne) ClearProviders() *GroupUpdateOne {
	_u.mutation.ClearProviders()
	return _u
}

// RemoveProviderIDs removes the "providers" edge to Provider entities by IDs.
func (_u *GroupUpdateOne) RemoveProviderIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.RemoveProviderIDs(ids...)
	return _u
}

// RemoveProviders removes "providers" edges to Provider entities.
func (_u *GroupUpdateOne) RemoveProviders(v ...*Provider) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProviderIDs(ids...)
}

// ClearAllowedUsers clears all "allowed_users" edges to the User entity.
func (_u *GroupUpdateOne) ClearAllowedUsers() *GroupUpdateOne {
	_u.mutation.ClearAllowedUsers()
	return _u
}

// RemoveAllowedUserIDs removes the "allowed_users" edge to User entities by IDs.
func (_u *GroupUpdateOne) RemoveAllowedUserIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.RemoveAllowedUserIDs(ids...)
	return _u
}

// RemoveAllowedUsers removes "allowed_users" edges to User entities.
func (_u *GroupUpdateOne) RemoveAllowedUsers(v ...*User) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllowedUserIDs(ids...)
}

// ClearDisabledPublicUsers clears all "disabled_public_users" edges to the User entity.
func (_u *GroupUpdateOne) ClearDisabledPublicUsers() *GroupUpdateOne {
	_u.mutation.ClearDisabledPublicUsers()
	return _u
}

// RemoveDisabledPublicUserIDs removes the "disabled_public_users" edge to User entities by IDs.
func (_u *GroupUpdateOne) RemoveDisabledPublicUserIDs(ids ...int64) *GroupUpdateOne {
	_u.mutation.RemoveDisabledPublicUserIDs(ids...)
	return _u
}

// RemoveDisabledPublicUsers removes "disabled_public_users" edges to User entities.
func (_u *GroupUpdateOne) RemoveDisabledPublicUsers(v ...*User) *GroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDisabledPublicUserIDs(ids...)
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdateOne) Where(ps ...predicate.Group) *GroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Group entity.
func (_u *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if group.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized group.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := group.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := group.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Group.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SchedulerType(); ok {
		if err := group.SchedulerTypeValidator(v); err != nil {
			return &ValidationError{Name: "scheduler_type", err: fmt.Errorf(`ent: validator failed for field "Group.scheduler_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayBrand(); ok {
		if err := group.DisplayBrandValidator(v); err != nil {
			return &ValidationError{Name: "display_brand", err: fmt.Errorf(`ent: validator failed for field "Group.display_brand": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultMappedModel(); ok {
		if err := group.DefaultMappedModelValidator(v); err != nil {
			return &ValidationError{Name: "default_mapped_model", err: fmt.Errorf(`ent: validator failed for field "Group.default_mapped_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxReasoningEffort(); ok {
		if err := group.MaxReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "max_reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "Group.max_reasoning_effort": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxReasoningEffortOverLimit(); ok {
		if err := group.MaxReasoningEffortOverLimitValidator(v); err != nil {
			return &ValidationError{Name: "max_reasoning_effort_over_limit", err: fmt.Errorf(`ent: validator failed for field "Group.max_reasoning_effort_over_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, group.FieldID)
		for _, f := range fields {
			if !group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(group.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(group.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Localization(); ok {
		_spec.SetField(group.FieldLocalization, field.TypeJSON, value)
	}
	if _u.mutation.LocalizationCleared() {
		_spec.ClearField(group.FieldLocalization, field.TypeJSON)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(group.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(group.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsExclusive(); ok {
		_spec.SetField(group.FieldIsExclusive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(group.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.DuplicateOperationIDCleared() {
		_spec.ClearField(group.FieldDuplicateOperationID, field.TypeString)
	}
	if value, ok := _u.mutation.SchedulerType(); ok {
		_spec.SetField(group.FieldSchedulerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdvancedSchedulerOverrides(); ok {
		_spec.SetField(group.FieldAdvancedSchedulerOverrides, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DisplayBrand(); ok {
		_spec.SetField(group.FieldDisplayBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowImageGeneration(); ok {
		_spec.SetField(group.FieldAllowImageGeneration, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowBatchImageGeneration(); ok {
		_spec.SetField(group.FieldAllowBatchImageGeneration, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RoutingPolicy(); ok {
		_spec.SetField(group.FieldRoutingPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoutingPolicy(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldRoutingPolicy, value)
		})
	}
	if _u.mutation.RoutingPolicyCleared() {
		_spec.ClearField(group.FieldRoutingPolicy, field.TypeJSON)
	}
	if value, ok := _u.mutation.ClaudeCodeOnly(); ok {
		_spec.SetField(group.FieldClaudeCodeOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FallbackGroupID(); ok {
		_spec.SetField(group.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupID(); ok {
		_spec.AddField(group.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if _u.mutation.FallbackGroupIDCleared() {
		_spec.ClearField(group.FieldFallbackGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FallbackGroupIDOnInvalidRequest(); ok {
		_spec.SetField(group.FieldFallbackGroupIDOnInvalidRequest, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupIDOnInvalidRequest(); ok {
		_spec.AddField(group.FieldFallbackGroupIDOnInvalidRequest, field.TypeInt64, value)
	}
	if _u.mutation.FallbackGroupIDOnInvalidRequestCleared() {
		_spec.ClearField(group.FieldFallbackGroupIDOnInvalidRequest, field.TypeInt64)
	}
	if value, ok := _u.mutation.UnavailableFallbackGroupID(); ok {
		_spec.SetField(group.FieldUnavailableFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnavailableFallbackGroupID(); ok {
		_spec.AddField(group.FieldUnavailableFallbackGroupID, field.TypeInt64, value)
	}
	if _u.mutation.UnavailableFallbackGroupIDCleared() {
		_spec.ClearField(group.FieldUnavailableFallbackGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ModelRouting(); ok {
		_spec.SetField(group.FieldModelRouting, field.TypeJSON, value)
	}
	if _u.mutation.ModelRoutingCleared() {
		_spec.ClearField(group.FieldModelRouting, field.TypeJSON)
	}
	if value, ok := _u.mutation.ModelRoutingEnabled(); ok {
		_spec.SetField(group.FieldModelRoutingEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.McpXMLInject(); ok {
		_spec.SetField(group.FieldMcpXMLInject, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportedModelScopes(); ok {
		_spec.SetField(group.FieldSupportedModelScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedModelScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldSupportedModelScopes, value)
		})
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(group.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(group.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowMessagesDispatch(); ok {
		_spec.SetField(group.FieldAllowMessagesDispatch, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowedProtocols(); ok {
		_spec.SetField(group.FieldAllowedProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldAllowedProtocols, value)
		})
	}
	if value, ok := _u.mutation.ProtocolFallbacks(); ok {
		_spec.SetField(group.FieldProtocolFallbacks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ResponsesImagePolicy(); ok {
		_spec.SetField(group.FieldResponsesImagePolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowLive(); ok {
		_spec.SetField(group.FieldAllowLive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OpenaiFastPolicy(); ok {
		_spec.SetField(group.FieldOpenaiFastPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForceOpenaiFast(); ok {
		_spec.SetField(group.FieldForceOpenaiFast, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireOauthOnly(); ok {
		_spec.SetField(group.FieldRequireOauthOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequirePrivacySet(); ok {
		_spec.SetField(group.FieldRequirePrivacySet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultMappedModel(); ok {
		_spec.SetField(group.FieldDefaultMappedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelsListConfig(); ok {
		_spec.SetField(group.FieldModelsListConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AvailabilityProbeConfig(); ok {
		_spec.SetField(group.FieldAvailabilityProbeConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(group.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(group.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxReasoningEffort(); ok {
		_spec.SetField(group.FieldMaxReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxReasoningEffortOverLimit(); ok {
		_spec.SetField(group.FieldMaxReasoningEffortOverLimit, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffortMappings(); ok {
		_spec.SetField(group.FieldReasoningEffortMappings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReasoningEffortMappings(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, group.FieldReasoningEffortMappings, value)
		})
	}
	if value, ok := _u.mutation.SessionIsolationEnabled(); ok {
		_spec.SetField(group.FieldSessionIsolationEnabled, field.TypeBool, value)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeysTable,
			Columns: []string{group.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeysTable,
			Columns: []string{group.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeysTable,
			Columns: []string{group.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCompositeGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeyCompositeGroupsTable,
			Columns: []string{group.APIKeyCompositeGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeyCompositeGroupsIDs(); len(nodes) > 0 && !_u.mutation.APIKeyCompositeGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeyCompositeGroupsTable,
			Columns: []string{group.APIKeyCompositeGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyCompositeGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeyCompositeGroupsTable,
			Columns: []string{group.APIKeyCompositeGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsageLogsTable,
			Columns: []string{group.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsageLogsTable,
			Columns: []string{group.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsageLogsTable,
			Columns: []string{group.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.ProvidersTable,
			Columns: group.ProvidersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProvidersIDs(); len(nodes) > 0 && !_u.mutation.ProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.ProvidersTable,
			Columns: group.ProvidersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.ProvidersTable,
			Columns: group.ProvidersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllowedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AllowedUsersTable,
			Columns: group.AllowedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &UserAllowedGroupCreate{config: _u.config, mutation: newUserAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllowedUsersIDs(); len(nodes) > 0 && !_u.mutation.AllowedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AllowedUsersTable,
			Columns: group.AllowedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserAllowedGroupCreate{config: _u.config, mutation: newUserAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllowedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AllowedUsersTable,
			Columns: group.AllowedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserAllowedGroupCreate{config: _u.config, mutation: newUserAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DisabledPublicUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.DisabledPublicUsersTable,
			Columns: group.DisabledPublicUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &UserDisabledPublicGroupCreate{config: _u.config, mutation: newUserDisabledPublicGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDisabledPublicUsersIDs(); len(nodes) > 0 && !_u.mutation.DisabledPublicUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.DisabledPublicUsersTable,
			Columns: group.DisabledPublicUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserDisabledPublicGroupCreate{config: _u.config, mutation: newUserDisabledPublicGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DisabledPublicUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.DisabledPublicUsersTable,
			Columns: group.DisabledPublicUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserDisabledPublicGroupCreate{config: _u.config, mutation: newUserDisabledPublicGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Group{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
