// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/internal/protocol"
	"github.com/TokenFlux/TokenRouter/internal/routing/accessview"
	"github.com/TokenFlux/TokenRouter/internal/scheduler/policy"
)

// Group is the model entity for the Group schema.
type Group struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Localization holds the value of the "localization" field.
	Localization accessview.GroupLocalization `json:"localization,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// IsExclusive holds the value of the "is_exclusive" field.
	IsExclusive bool `json:"is_exclusive,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// 内部幂等恢复标识，不对 API 暴露
	DuplicateOperationID *string `json:"duplicate_operation_id,omitempty"`
	// 分组调度器类型：basic 或 advanced
	SchedulerType string `json:"scheduler_type,omitempty"`
	// 分组高级调度器稀疏覆盖；未设置字段继承网关通用设置
	AdvancedSchedulerOverrides policy.GroupAdvancedSchedulerOverrides `json:"advanced_scheduler_overrides,omitempty"`
	// 模型广场展示品牌
	DisplayBrand string `json:"display_brand,omitempty"`
	// 是否允许该分组使用图片生成能力
	AllowImageGeneration bool `json:"allow_image_generation,omitempty"`
	// 是否允许该分组使用批量图片生成能力
	AllowBatchImageGeneration bool `json:"allow_batch_image_generation,omitempty"`
	// 分组独立模型与功能策略
	RoutingPolicy jsontext.Value `json:"routing_policy,omitempty"`
	// 是否仅允许 Claude Code 客户端
	ClaudeCodeOnly bool `json:"claude_code_only,omitempty"`
	// 非 Claude Code 请求降级使用的分组 ID
	FallbackGroupID *int64 `json:"fallback_group_id,omitempty"`
	// 无效请求兜底使用的分组 ID
	FallbackGroupIDOnInvalidRequest *int64 `json:"fallback_group_id_on_invalid_request,omitempty"`
	// 当前分组不可用时优先回退使用的分组 ID
	UnavailableFallbackGroupID *int64 `json:"unavailable_fallback_group_id,omitempty"`
	// 模型路由配置：模型模式 -> 优先提供商ID列表
	ModelRouting map[string][]int64 `json:"model_routing,omitempty"`
	// 是否启用模型路由配置
	ModelRoutingEnabled bool `json:"model_routing_enabled,omitempty"`
	// 是否注入 MCP XML 调用协议提示词（仅 antigravity 平台）
	McpXMLInject bool `json:"mcp_xml_inject,omitempty"`
	// 支持的模型系列：claude, gemini_text, gemini_image
	SupportedModelScopes []string `json:"supported_model_scopes,omitempty"`
	// 分组显示排序，数值越小越靠前
	SortOrder int `json:"sort_order,omitempty"`
	// 是否允许 /v1/messages 调度到此 OpenAI 分组
	AllowMessagesDispatch bool `json:"allow_messages_dispatch,omitempty"`
	// 允许客户端调用分组的协议与业务入口完整集合
	AllowedProtocols []protocol.ProtocolID `json:"allowed_protocols,omitempty"`
	// ProtocolFallbacks holds the value of the "protocol_fallbacks" field.
	ProtocolFallbacks map[protocol.ProtocolID][]protocol.ProtocolID `json:"protocol_fallbacks,omitempty"`
	// ResponsesImagePolicy holds the value of the "responses_image_policy" field.
	ResponsesImagePolicy string `json:"responses_image_policy,omitempty"`
	// 是否允许此 OpenAI 分组访问 Live 接口
	AllowLive bool `json:"allow_live,omitempty"`
	// 分组加速策略：follow_request/force_priority/force_ultrafast/force_off
	OpenaiFastPolicy string `json:"openai_fast_policy,omitempty"`
	// 是否强制此 OpenAI 分组请求使用 service_tier=priority
	ForceOpenaiFast bool `json:"force_openai_fast,omitempty"`
	// 仅允许非 apikey 类型提供商关联到此分组
	RequireOauthOnly bool `json:"require_oauth_only,omitempty"`
	// 调度时仅允许 privacy 已成功设置的提供商
	RequirePrivacySet bool `json:"require_privacy_set,omitempty"`
	// 默认映射模型 ID，当提供商级映射找不到时使用此值
	DefaultMappedModel string `json:"default_mapped_model,omitempty"`
	// 自定义 /v1/models 展示列表配置；仅影响模型列表响应，不影响调度
	ModelsListConfig accessview.GroupModelsListConfig `json:"models_list_config,omitempty"`
	// 分组主动可用性探测配置
	AvailabilityProbeConfig accessview.GroupAvailabilityProbeConfig `json:"availability_probe_config,omitempty"`
	// 分组 RPM 上限，0 表示不限制；设置后接管该分组用户的限流
	RpmLimit int `json:"rpm_limit,omitempty"`
	// OpenAI reasoning effort 上限；可选 minimal/low/medium/high/xhigh/max
	MaxReasoningEffort string `json:"max_reasoning_effort,omitempty"`
	// 超过推理强度上限时的访问控制：downgrade 自动降档，deny 拒绝访问
	MaxReasoningEffortOverLimit string `json:"max_reasoning_effort_over_limit,omitempty"`
	// OpenAI reasoning effort 自定义映射；可按模型精确名、前缀或后缀限定，先映射再应用上限
	ReasoningEffortMappings []accessview.ReasoningEffortMapping `json:"reasoning_effort_mappings,omitempty"`
	// 是否开启会话隔离
	SessionIsolationEnabled bool `json:"session_isolation_enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupQuery when eager-loading is set.
	Edges        GroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupEdges holds the relations/edges for other nodes in the graph.
type GroupEdges struct {
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// APIKeyCompositeGroups holds the value of the api_key_composite_groups edge.
	APIKeyCompositeGroups []*APIKeyCompositeGroup `json:"api_key_composite_groups,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// Providers holds the value of the providers edge.
	Providers []*Provider `json:"providers,omitempty"`
	// AllowedUsers holds the value of the allowed_users edge.
	AllowedUsers []*User `json:"allowed_users,omitempty"`
	// DisabledPublicUsers holds the value of the disabled_public_users edge.
	DisabledPublicUsers []*User `json:"disabled_public_users,omitempty"`
	// ProviderGroups holds the value of the provider_groups edge.
	ProviderGroups []*ProviderGroup `json:"provider_groups,omitempty"`
	// UserAllowedGroups holds the value of the user_allowed_groups edge.
	UserAllowedGroups []*UserAllowedGroup `json:"user_allowed_groups,omitempty"`
	// UserDisabledPublicGroups holds the value of the user_disabled_public_groups edge.
	UserDisabledPublicGroups []*UserDisabledPublicGroup `json:"user_disabled_public_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [9]bool
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[0] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// APIKeyCompositeGroupsOrErr returns the APIKeyCompositeGroups value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) APIKeyCompositeGroupsOrErr() ([]*APIKeyCompositeGroup, error) {
	if e.loadedTypes[1] {
		return e.APIKeyCompositeGroups, nil
	}
	return nil, &NotLoadedError{edge: "api_key_composite_groups"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[2] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// ProvidersOrErr returns the Providers value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) ProvidersOrErr() ([]*Provider, error) {
	if e.loadedTypes[3] {
		return e.Providers, nil
	}
	return nil, &NotLoadedError{edge: "providers"}
}

// AllowedUsersOrErr returns the AllowedUsers value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) AllowedUsersOrErr() ([]*User, error) {
	if e.loadedTypes[4] {
		return e.AllowedUsers, nil
	}
	return nil, &NotLoadedError{edge: "allowed_users"}
}

// DisabledPublicUsersOrErr returns the DisabledPublicUsers value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) DisabledPublicUsersOrErr() ([]*User, error) {
	if e.loadedTypes[5] {
		return e.DisabledPublicUsers, nil
	}
	return nil, &NotLoadedError{edge: "disabled_public_users"}
}

// ProviderGroupsOrErr returns the ProviderGroups value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) ProviderGroupsOrErr() ([]*ProviderGroup, error) {
	if e.loadedTypes[6] {
		return e.ProviderGroups, nil
	}
	return nil, &NotLoadedError{edge: "provider_groups"}
}

// UserAllowedGroupsOrErr returns the UserAllowedGroups value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) UserAllowedGroupsOrErr() ([]*UserAllowedGroup, error) {
	if e.loadedTypes[7] {
		return e.UserAllowedGroups, nil
	}
	return nil, &NotLoadedError{edge: "user_allowed_groups"}
}

// UserDisabledPublicGroupsOrErr returns the UserDisabledPublicGroups value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) UserDisabledPublicGroupsOrErr() ([]*UserDisabledPublicGroup, error) {
	if e.loadedTypes[8] {
		return e.UserDisabledPublicGroups, nil
	}
	return nil, &NotLoadedError{edge: "user_disabled_public_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Group) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case group.FieldLocalization, group.FieldAdvancedSchedulerOverrides, group.FieldRoutingPolicy, group.FieldModelRouting, group.FieldSupportedModelScopes, group.FieldAllowedProtocols, group.FieldProtocolFallbacks, group.FieldModelsListConfig, group.FieldAvailabilityProbeConfig, group.FieldReasoningEffortMappings:
			values[i] = new([]byte)
		case group.FieldIsExclusive, group.FieldAllowImageGeneration, group.FieldAllowBatchImageGeneration, group.FieldClaudeCodeOnly, group.FieldModelRoutingEnabled, group.FieldMcpXMLInject, group.FieldAllowMessagesDispatch, group.FieldAllowLive, group.FieldForceOpenaiFast, group.FieldRequireOauthOnly, group.FieldRequirePrivacySet, group.FieldSessionIsolationEnabled:
			values[i] = new(sql.NullBool)
		case group.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case group.FieldID, group.FieldFallbackGroupID, group.FieldFallbackGroupIDOnInvalidRequest, group.FieldUnavailableFallbackGroupID, group.FieldSortOrder, group.FieldRpmLimit:
			values[i] = new(sql.NullInt64)
		case group.FieldName, group.FieldDescription, group.FieldStatus, group.FieldDuplicateOperationID, group.FieldSchedulerType, group.FieldDisplayBrand, group.FieldResponsesImagePolicy, group.FieldOpenaiFastPolicy, group.FieldDefaultMappedModel, group.FieldMaxReasoningEffort, group.FieldMaxReasoningEffortOverLimit:
			values[i] = new(sql.NullString)
		case group.FieldCreatedAt, group.FieldUpdatedAt, group.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Group fields.
func (_m *Group) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case group.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case group.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case group.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case group.FieldLocalization:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field localization", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Localization); err != nil {
					return fmt.Errorf("unmarshal field localization: %w", err)
				}
			}
		case group.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case group.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case group.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case group.FieldIsExclusive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_exclusive", values[i])
			} else if value.Valid {
				_m.IsExclusive = value.Bool
			}
		case group.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case group.FieldDuplicateOperationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_operation_id", values[i])
			} else if value.Valid {
				_m.DuplicateOperationID = new(string)
				*_m.DuplicateOperationID = value.String
			}
		case group.FieldSchedulerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scheduler_type", values[i])
			} else if value.Valid {
				_m.SchedulerType = value.String
			}
		case group.FieldAdvancedSchedulerOverrides:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field advanced_scheduler_overrides", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AdvancedSchedulerOverrides); err != nil {
					return fmt.Errorf("unmarshal field advanced_scheduler_overrides: %w", err)
				}
			}
		case group.FieldDisplayBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_brand", values[i])
			} else if value.Valid {
				_m.DisplayBrand = value.String
			}
		case group.FieldAllowImageGeneration:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_image_generation", values[i])
			} else if value.Valid {
				_m.AllowImageGeneration = value.Bool
			}
		case group.FieldAllowBatchImageGeneration:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_batch_image_generation", values[i])
			} else if value.Valid {
				_m.AllowBatchImageGeneration = value.Bool
			}
		case group.FieldRoutingPolicy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field routing_policy", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RoutingPolicy); err != nil {
					return fmt.Errorf("unmarshal field routing_policy: %w", err)
				}
			}
		case group.FieldClaudeCodeOnly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field claude_code_only", values[i])
			} else if value.Valid {
				_m.ClaudeCodeOnly = value.Bool
			}
		case group.FieldFallbackGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_group_id", values[i])
			} else if value.Valid {
				_m.FallbackGroupID = new(int64)
				*_m.FallbackGroupID = value.Int64
			}
		case group.FieldFallbackGroupIDOnInvalidRequest:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_group_id_on_invalid_request", values[i])
			} else if value.Valid {
				_m.FallbackGroupIDOnInvalidRequest = new(int64)
				*_m.FallbackGroupIDOnInvalidRequest = value.Int64
			}
		case group.FieldUnavailableFallbackGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unavailable_fallback_group_id", values[i])
			} else if value.Valid {
				_m.UnavailableFallbackGroupID = new(int64)
				*_m.UnavailableFallbackGroupID = value.Int64
			}
		case group.FieldModelRouting:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_routing", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelRouting); err != nil {
					return fmt.Errorf("unmarshal field model_routing: %w", err)
				}
			}
		case group.FieldModelRoutingEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field model_routing_enabled", values[i])
			} else if value.Valid {
				_m.ModelRoutingEnabled = value.Bool
			}
		case group.FieldMcpXMLInject:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mcp_xml_inject", values[i])
			} else if value.Valid {
				_m.McpXMLInject = value.Bool
			}
		case group.FieldSupportedModelScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field supported_model_scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SupportedModelScopes); err != nil {
					return fmt.Errorf("unmarshal field supported_model_scopes: %w", err)
				}
			}
		case group.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case group.FieldAllowMessagesDispatch:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_messages_dispatch", values[i])
			} else if value.Valid {
				_m.AllowMessagesDispatch = value.Bool
			}
		case group.FieldAllowedProtocols:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_protocols", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedProtocols); err != nil {
					return fmt.Errorf("unmarshal field allowed_protocols: %w", err)
				}
			}
		case group.FieldProtocolFallbacks:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field protocol_fallbacks", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProtocolFallbacks); err != nil {
					return fmt.Errorf("unmarshal field protocol_fallbacks: %w", err)
				}
			}
		case group.FieldResponsesImagePolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field responses_image_policy", values[i])
			} else if value.Valid {
				_m.ResponsesImagePolicy = value.String
			}
		case group.FieldAllowLive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_live", values[i])
			} else if value.Valid {
				_m.AllowLive = value.Bool
			}
		case group.FieldOpenaiFastPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field openai_fast_policy", values[i])
			} else if value.Valid {
				_m.OpenaiFastPolicy = value.String
			}
		case group.FieldForceOpenaiFast:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field force_openai_fast", values[i])
			} else if value.Valid {
				_m.ForceOpenaiFast = value.Bool
			}
		case group.FieldRequireOauthOnly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_oauth_only", values[i])
			} else if value.Valid {
				_m.RequireOauthOnly = value.Bool
			}
		case group.FieldRequirePrivacySet:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_privacy_set", values[i])
			} else if value.Valid {
				_m.RequirePrivacySet = value.Bool
			}
		case group.FieldDefaultMappedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_mapped_model", values[i])
			} else if value.Valid {
				_m.DefaultMappedModel = value.String
			}
		case group.FieldModelsListConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field models_list_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelsListConfig); err != nil {
					return fmt.Errorf("unmarshal field models_list_config: %w", err)
				}
			}
		case group.FieldAvailabilityProbeConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field availability_probe_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AvailabilityProbeConfig); err != nil {
					return fmt.Errorf("unmarshal field availability_probe_config: %w", err)
				}
			}
		case group.FieldRpmLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rpm_limit", values[i])
			} else if value.Valid {
				_m.RpmLimit = int(value.Int64)
			}
		case group.FieldMaxReasoningEffort:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field max_reasoning_effort", values[i])
			} else if value.Valid {
				_m.MaxReasoningEffort = value.String
			}
		case group.FieldMaxReasoningEffortOverLimit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field max_reasoning_effort_over_limit", values[i])
			} else if value.Valid {
				_m.MaxReasoningEffortOverLimit = value.String
			}
		case group.FieldReasoningEffortMappings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_effort_mappings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ReasoningEffortMappings); err != nil {
					return fmt.Errorf("unmarshal field reasoning_effort_mappings: %w", err)
				}
			}
		case group.FieldSessionIsolationEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field session_isolation_enabled", values[i])
			} else if value.Valid {
				_m.SessionIsolationEnabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Group.
// This includes values selected through modifiers, order, etc.
func (_m *Group) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKeys queries the "api_keys" edge of the Group entity.
func (_m *Group) QueryAPIKeys() *APIKeyQuery {
	return NewGroupClient(_m.config).QueryAPIKeys(_m)
}

// QueryAPIKeyCompositeGroups queries the "api_key_composite_groups" edge of the Group entity.
func (_m *Group) QueryAPIKeyCompositeGroups() *APIKeyCompositeGroupQuery {
	return NewGroupClient(_m.config).QueryAPIKeyCompositeGroups(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the Group entity.
func (_m *Group) QueryUsageLogs() *UsageLogQuery {
	return NewGroupClient(_m.config).QueryUsageLogs(_m)
}

// QueryProviders queries the "providers" edge of the Group entity.
func (_m *Group) QueryProviders() *ProviderQuery {
	return NewGroupClient(_m.config).QueryProviders(_m)
}

// QueryAllowedUsers queries the "allowed_users" edge of the Group entity.
func (_m *Group) QueryAllowedUsers() *UserQuery {
	return NewGroupClient(_m.config).QueryAllowedUsers(_m)
}

// QueryDisabledPublicUsers queries the "disabled_public_users" edge of the Group entity.
func (_m *Group) QueryDisabledPublicUsers() *UserQuery {
	return NewGroupClient(_m.config).QueryDisabledPublicUsers(_m)
}

// QueryProviderGroups queries the "provider_groups" edge of the Group entity.
func (_m *Group) QueryProviderGroups() *ProviderGroupQuery {
	return NewGroupClient(_m.config).QueryProviderGroups(_m)
}

// QueryUserAllowedGroups queries the "user_allowed_groups" edge of the Group entity.
func (_m *Group) QueryUserAllowedGroups() *UserAllowedGroupQuery {
	return NewGroupClient(_m.config).QueryUserAllowedGroups(_m)
}

// QueryUserDisabledPublicGroups queries the "user_disabled_public_groups" edge of the Group entity.
func (_m *Group) QueryUserDisabledPublicGroups() *UserDisabledPublicGroupQuery {
	return NewGroupClient(_m.config).QueryUserDisabledPublicGroups(_m)
}

// Update returns a builder for updating this Group.
// Note that you need to call Group.Unwrap() before calling this method if this Group
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Group) Update() *GroupUpdateOne {
	return NewGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Group entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Group) Unwrap() *Group {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Group is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Group) String() string {
	var builder strings.Builder
	builder.WriteString("Group(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("localization=")
	builder.WriteString(fmt.Sprintf("%v", _m.Localization))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("is_exclusive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsExclusive))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.DuplicateOperationID; v != nil {
		builder.WriteString("duplicate_operation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("scheduler_type=")
	builder.WriteString(_m.SchedulerType)
	builder.WriteString(", ")
	builder.WriteString("advanced_scheduler_overrides=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdvancedSchedulerOverrides))
	builder.WriteString(", ")
	builder.WriteString("display_brand=")
	builder.WriteString(_m.DisplayBrand)
	builder.WriteString(", ")
	builder.WriteString("allow_image_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowImageGeneration))
	builder.WriteString(", ")
	builder.WriteString("allow_batch_image_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowBatchImageGeneration))
	builder.WriteString(", ")
	builder.WriteString("routing_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoutingPolicy))
	builder.WriteString(", ")
	builder.WriteString("claude_code_only=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClaudeCodeOnly))
	builder.WriteString(", ")
	if v := _m.FallbackGroupID; v != nil {
		builder.WriteString("fallback_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FallbackGroupIDOnInvalidRequest; v != nil {
		builder.WriteString("fallback_group_id_on_invalid_request=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UnavailableFallbackGroupID; v != nil {
		builder.WriteString("unavailable_fallback_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("model_routing=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelRouting))
	builder.WriteString(", ")
	builder.WriteString("model_routing_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelRoutingEnabled))
	builder.WriteString(", ")
	builder.WriteString("mcp_xml_inject=")
	builder.WriteString(fmt.Sprintf("%v", _m.McpXMLInject))
	builder.WriteString(", ")
	builder.WriteString("supported_model_scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportedModelScopes))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("allow_messages_dispatch=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowMessagesDispatch))
	builder.WriteString(", ")
	builder.WriteString("allowed_protocols=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedProtocols))
	builder.WriteString(", ")
	builder.WriteString("protocol_fallbacks=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProtocolFallbacks))
	builder.WriteString(", ")
	builder.WriteString("responses_image_policy=")
	builder.WriteString(_m.ResponsesImagePolicy)
	builder.WriteString(", ")
	builder.WriteString("allow_live=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowLive))
	builder.WriteString(", ")
	builder.WriteString("openai_fast_policy=")
	builder.WriteString(_m.OpenaiFastPolicy)
	builder.WriteString(", ")
	builder.WriteString("force_openai_fast=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForceOpenaiFast))
	builder.WriteString(", ")
	builder.WriteString("require_oauth_only=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequireOauthOnly))
	builder.WriteString(", ")
	builder.WriteString("require_privacy_set=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequirePrivacySet))
	builder.WriteString(", ")
	builder.WriteString("default_mapped_model=")
	builder.WriteString(_m.DefaultMappedModel)
	builder.WriteString(", ")
	builder.WriteString("models_list_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelsListConfig))
	builder.WriteString(", ")
	builder.WriteString("availability_probe_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailabilityProbeConfig))
	builder.WriteString(", ")
	builder.WriteString("rpm_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.RpmLimit))
	builder.WriteString(", ")
	builder.WriteString("max_reasoning_effort=")
	builder.WriteString(_m.MaxReasoningEffort)
	builder.WriteString(", ")
	builder.WriteString("max_reasoning_effort_over_limit=")
	builder.WriteString(_m.MaxReasoningEffortOverLimit)
	builder.WriteString(", ")
	builder.WriteString("reasoning_effort_mappings=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReasoningEffortMappings))
	builder.WriteString(", ")
	builder.WriteString("session_isolation_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionIsolationEnabled))
	builder.WriteByte(')')
	return builder.String()
}

// Groups is a parsable slice of Group.
type Groups []*Group
