// Code generated by ent, DO NOT EDIT.

package group

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/TokenFlux/TokenRouter/internal/protocol"
	"github.com/TokenFlux/TokenRouter/internal/routing/accessview"
	"github.com/TokenFlux/TokenRouter/internal/scheduler/policy"
)

const (
	// Label holds the string label denoting the group type in the database.
	Label = "group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldLocalization holds the string denoting the localization field in the database.
	FieldLocalization = "localization"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldRateMultiplier holds the string denoting the rate_multiplier field in the database.
	FieldRateMultiplier = "rate_multiplier"
	// FieldIsExclusive holds the string denoting the is_exclusive field in the database.
	FieldIsExclusive = "is_exclusive"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDuplicateOperationID holds the string denoting the duplicate_operation_id field in the database.
	FieldDuplicateOperationID = "duplicate_operation_id"
	// FieldSchedulerType holds the string denoting the scheduler_type field in the database.
	FieldSchedulerType = "scheduler_type"
	// FieldAdvancedSchedulerOverrides holds the string denoting the advanced_scheduler_overrides field in the database.
	FieldAdvancedSchedulerOverrides = "advanced_scheduler_overrides"
	// FieldDisplayBrand holds the string denoting the display_brand field in the database.
	FieldDisplayBrand = "display_brand"
	// FieldAllowImageGeneration holds the string denoting the allow_image_generation field in the database.
	FieldAllowImageGeneration = "allow_image_generation"
	// FieldAllowBatchImageGeneration holds the string denoting the allow_batch_image_generation field in the database.
	FieldAllowBatchImageGeneration = "allow_batch_image_generation"
	// FieldRoutingPolicy holds the string denoting the routing_policy field in the database.
	FieldRoutingPolicy = "routing_policy"
	// FieldClaudeCodeOnly holds the string denoting the claude_code_only field in the database.
	FieldClaudeCodeOnly = "claude_code_only"
	// FieldFallbackGroupID holds the string denoting the fallback_group_id field in the database.
	FieldFallbackGroupID = "fallback_group_id"
	// FieldFallbackGroupIDOnInvalidRequest holds the string denoting the fallback_group_id_on_invalid_request field in the database.
	FieldFallbackGroupIDOnInvalidRequest = "fallback_group_id_on_invalid_request"
	// FieldUnavailableFallbackGroupID holds the string denoting the unavailable_fallback_group_id field in the database.
	FieldUnavailableFallbackGroupID = "unavailable_fallback_group_id"
	// FieldModelRouting holds the string denoting the model_routing field in the database.
	FieldModelRouting = "model_routing"
	// FieldModelRoutingEnabled holds the string denoting the model_routing_enabled field in the database.
	FieldModelRoutingEnabled = "model_routing_enabled"
	// FieldMcpXMLInject holds the string denoting the mcp_xml_inject field in the database.
	FieldMcpXMLInject = "mcp_xml_inject"
	// FieldSupportedModelScopes holds the string denoting the supported_model_scopes field in the database.
	FieldSupportedModelScopes = "supported_model_scopes"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldAllowMessagesDispatch holds the string denoting the allow_messages_dispatch field in the database.
	FieldAllowMessagesDispatch = "allow_messages_dispatch"
	// FieldAllowedProtocols holds the string denoting the allowed_protocols field in the database.
	FieldAllowedProtocols = "allowed_protocols"
	// FieldProtocolFallbacks holds the string denoting the protocol_fallbacks field in the database.
	FieldProtocolFallbacks = "protocol_fallbacks"
	// FieldResponsesImagePolicy holds the string denoting the responses_image_policy field in the database.
	FieldResponsesImagePolicy = "responses_image_policy"
	// FieldAllowLive holds the string denoting the allow_live field in the database.
	FieldAllowLive = "allow_live"
	// FieldOpenaiFastPolicy holds the string denoting the openai_fast_policy field in the database.
	FieldOpenaiFastPolicy = "openai_fast_policy"
	// FieldForceOpenaiFast holds the string denoting the force_openai_fast field in the database.
	FieldForceOpenaiFast = "force_openai_fast"
	// FieldRequireOauthOnly holds the string denoting the require_oauth_only field in the database.
	FieldRequireOauthOnly = "require_oauth_only"
	// FieldRequirePrivacySet holds the string denoting the require_privacy_set field in the database.
	FieldRequirePrivacySet = "require_privacy_set"
	// FieldDefaultMappedModel holds the string denoting the default_mapped_model field in the database.
	FieldDefaultMappedModel = "default_mapped_model"
	// FieldModelsListConfig holds the string denoting the models_list_config field in the database.
	FieldModelsListConfig = "models_list_config"
	// FieldAvailabilityProbeConfig holds the string denoting the availability_probe_config field in the database.
	FieldAvailabilityProbeConfig = "availability_probe_config"
	// FieldRpmLimit holds the string denoting the rpm_limit field in the database.
	FieldRpmLimit = "rpm_limit"
	// FieldMaxReasoningEffort holds the string denoting the max_reasoning_effort field in the database.
	FieldMaxReasoningEffort = "max_reasoning_effort"
	// FieldMaxReasoningEffortOverLimit holds the string denoting the max_reasoning_effort_over_limit field in the database.
	FieldMaxReasoningEffortOverLimit = "max_reasoning_effort_over_limit"
	// FieldReasoningEffortMappings holds the string denoting the reasoning_effort_mappings field in the database.
	FieldReasoningEffortMappings = "reasoning_effort_mappings"
	// FieldSessionIsolationEnabled holds the string denoting the session_isolation_enabled field in the database.
	FieldSessionIsolationEnabled = "session_isolation_enabled"
	// EdgeAPIKeys holds the string denoting the api_keys edge name in mutations.
	EdgeAPIKeys = "api_keys"
	// EdgeAPIKeyCompositeGroups holds the string denoting the api_key_composite_groups edge name in mutations.
	EdgeAPIKeyCompositeGroups = "api_key_composite_groups"
	// EdgeUsageLogs holds the string denoting the usage_logs edge name in mutations.
	EdgeUsageLogs = "usage_logs"
	// EdgeProviders holds the string denoting the providers edge name in mutations.
	EdgeProviders = "providers"
	// EdgeAllowedUsers holds the string denoting the allowed_users edge name in mutations.
	EdgeAllowedUsers = "allowed_users"
	// EdgeDisabledPublicUsers holds the string denoting the disabled_public_users edge name in mutations.
	EdgeDisabledPublicUsers = "disabled_public_users"
	// EdgeProviderGroups holds the string denoting the provider_groups edge name in mutations.
	EdgeProviderGroups = "provider_groups"
	// EdgeUserAllowedGroups holds the string denoting the user_allowed_groups edge name in mutations.
	EdgeUserAllowedGroups = "user_allowed_groups"
	// EdgeUserDisabledPublicGroups holds the string denoting the user_disabled_public_groups edge name in mutations.
	EdgeUserDisabledPublicGroups = "user_disabled_public_groups"
	// Table holds the table name of the group in the database.
	Table = "groups"
	// APIKeysTable is the table that holds the api_keys relation/edge.
	APIKeysTable = "api_keys"
	// APIKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeysInverseTable = "api_keys"
	// APIKeysColumn is the table column denoting the api_keys relation/edge.
	APIKeysColumn = "group_id"
	// APIKeyCompositeGroupsTable is the table that holds the api_key_composite_groups relation/edge.
	APIKeyCompositeGroupsTable = "api_key_composite_groups"
	// APIKeyCompositeGroupsInverseTable is the table name for the APIKeyCompositeGroup entity.
	// It exists in this package in order to avoid circular dependency with the "apikeycompositegroup" package.
	APIKeyCompositeGroupsInverseTable = "api_key_composite_groups"
	// APIKeyCompositeGroupsColumn is the table column denoting the api_key_composite_groups relation/edge.
	APIKeyCompositeGroupsColumn = "group_id"
	// UsageLogsTable is the table that holds the usage_logs relation/edge.
	UsageLogsTable = "usage_logs"
	// UsageLogsInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogsInverseTable = "usage_logs"
	// UsageLogsColumn is the table column denoting the usage_logs relation/edge.
	UsageLogsColumn = "group_id"
	// ProvidersTable is the table that holds the providers relation/edge. The primary key declared below.
	ProvidersTable = "provider_groups"
	// ProvidersInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	ProvidersInverseTable = "providers"
	// AllowedUsersTable is the table that holds the allowed_users relation/edge. The primary key declared below.
	AllowedUsersTable = "user_allowed_groups"
	// AllowedUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AllowedUsersInverseTable = "users"
	// DisabledPublicUsersTable is the table that holds the disabled_public_users relation/edge. The primary key declared below.
	DisabledPublicUsersTable = "user_disabled_public_groups"
	// DisabledPublicUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DisabledPublicUsersInverseTable = "users"
	// ProviderGroupsTable is the table that holds the provider_groups relation/edge.
	ProviderGroupsTable = "provider_groups"
	// ProviderGroupsInverseTable is the table name for the ProviderGroup entity.
	// It exists in this package in order to avoid circular dependency with the "providergroup" package.
	ProviderGroupsInverseTable = "provider_groups"
	// ProviderGroupsColumn is the table column denoting the provider_groups relation/edge.
	ProviderGroupsColumn = "group_id"
	// UserAllowedGroupsTable is the table that holds the user_allowed_groups relation/edge.
	UserAllowedGroupsTable = "user_allowed_groups"
	// UserAllowedGroupsInverseTable is the table name for the UserAllowedGroup entity.
	// It exists in this package in order to avoid circular dependency with the "userallowedgroup" package.
	UserAllowedGroupsInverseTable = "user_allowed_groups"
	// UserAllowedGroupsColumn is the table column denoting the user_allowed_groups relation/edge.
	UserAllowedGroupsColumn = "group_id"
	// UserDisabledPublicGroupsTable is the table that holds the user_disabled_public_groups relation/edge.
	UserDisabledPublicGroupsTable = "user_disabled_public_groups"
	// UserDisabledPublicGroupsInverseTable is the table name for the UserDisabledPublicGroup entity.
	// It exists in this package in order to avoid circular dependency with the "userdisabledpublicgroup" package.
	UserDisabledPublicGroupsInverseTable = "user_disabled_public_groups"
	// UserDisabledPublicGroupsColumn is the table column denoting the user_disabled_public_groups relation/edge.
	UserDisabledPublicGroupsColumn = "group_id"
)

// Columns holds all SQL columns for group fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldLocalization,
	FieldName,
	FieldDescription,
	FieldRateMultiplier,
	FieldIsExclusive,
	FieldStatus,
	FieldDuplicateOperationID,
	FieldSchedulerType,
	FieldAdvancedSchedulerOverrides,
	FieldDisplayBrand,
	FieldAllowImageGeneration,
	FieldAllowBatchImageGeneration,
	FieldRoutingPolicy,
	FieldClaudeCodeOnly,
	FieldFallbackGroupID,
	FieldFallbackGroupIDOnInvalidRequest,
	FieldUnavailableFallbackGroupID,
	FieldModelRouting,
	FieldModelRoutingEnabled,
	FieldMcpXMLInject,
	FieldSupportedModelScopes,
	FieldSortOrder,
	FieldAllowMessagesDispatch,
	FieldAllowedProtocols,
	FieldProtocolFallbacks,
	FieldResponsesImagePolicy,
	FieldAllowLive,
	FieldOpenaiFastPolicy,
	FieldForceOpenaiFast,
	FieldRequireOauthOnly,
	FieldRequirePrivacySet,
	FieldDefaultMappedModel,
	FieldModelsListConfig,
	FieldAvailabilityProbeConfig,
	FieldRpmLimit,
	FieldMaxReasoningEffort,
	FieldMaxReasoningEffortOverLimit,
	FieldReasoningEffortMappings,
	FieldSessionIsolationEnabled,
}

var (
	// ProvidersPrimaryKey and ProvidersColumn2 are the table columns denoting the
	// primary key for the providers relation (M2M).
	ProvidersPrimaryKey = []string{"provider_id", "group_id"}
	// AllowedUsersPrimaryKey and AllowedUsersColumn2 are the table columns denoting the
	// primary key for the allowed_users relation (M2M).
	AllowedUsersPrimaryKey = []string{"user_id", "group_id"}
	// DisabledPublicUsersPrimaryKey and DisabledPublicUsersColumn2 are the table columns denoting the
	// primary key for the disabled_public_users relation (M2M).
	DisabledPublicUsersPrimaryKey = []string{"user_id", "group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/TokenFlux/TokenRouter/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultRateMultiplier holds the default value on creation for the "rate_multiplier" field.
	DefaultRateMultiplier float64
	// DefaultIsExclusive holds the default value on creation for the "is_exclusive" field.
	DefaultIsExclusive bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DuplicateOperationIDValidator is a validator for the "duplicate_operation_id" field. It is called by the builders before save.
	DuplicateOperationIDValidator func(string) error
	// DefaultSchedulerType holds the default value on creation for the "scheduler_type" field.
	DefaultSchedulerType string
	// SchedulerTypeValidator is a validator for the "scheduler_type" field. It is called by the builders before save.
	SchedulerTypeValidator func(string) error
	// DefaultAdvancedSchedulerOverrides holds the default value on creation for the "advanced_scheduler_overrides" field.
	DefaultAdvancedSchedulerOverrides policy.GroupAdvancedSchedulerOverrides
	// DefaultDisplayBrand holds the default value on creation for the "display_brand" field.
	DefaultDisplayBrand string
	// DisplayBrandValidator is a validator for the "display_brand" field. It is called by the builders before save.
	DisplayBrandValidator func(string) error
	// DefaultAllowImageGeneration holds the default value on creation for the "allow_image_generation" field.
	DefaultAllowImageGeneration bool
	// DefaultAllowBatchImageGeneration holds the default value on creation for the "allow_batch_image_generation" field.
	DefaultAllowBatchImageGeneration bool
	// DefaultClaudeCodeOnly holds the default value on creation for the "claude_code_only" field.
	DefaultClaudeCodeOnly bool
	// DefaultModelRoutingEnabled holds the default value on creation for the "model_routing_enabled" field.
	DefaultModelRoutingEnabled bool
	// DefaultMcpXMLInject holds the default value on creation for the "mcp_xml_inject" field.
	DefaultMcpXMLInject bool
	// DefaultSupportedModelScopes holds the default value on creation for the "supported_model_scopes" field.
	DefaultSupportedModelScopes []string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultAllowMessagesDispatch holds the default value on creation for the "allow_messages_dispatch" field.
	DefaultAllowMessagesDispatch bool
	// DefaultAllowedProtocols holds the default value on creation for the "allowed_protocols" field.
	DefaultAllowedProtocols []protocol.ProtocolID
	// DefaultProtocolFallbacks holds the default value on creation for the "protocol_fallbacks" field.
	DefaultProtocolFallbacks map[protocol.ProtocolID][]protocol.ProtocolID
	// DefaultResponsesImagePolicy holds the default value on creation for the "responses_image_policy" field.
	DefaultResponsesImagePolicy string
	// DefaultAllowLive holds the default value on creation for the "allow_live" field.
	DefaultAllowLive bool
	// DefaultOpenaiFastPolicy holds the default value on creation for the "openai_fast_policy" field.
	DefaultOpenaiFastPolicy string
	// DefaultForceOpenaiFast holds the default value on creation for the "force_openai_fast" field.
	DefaultForceOpenaiFast bool
	// DefaultRequireOauthOnly holds the default value on creation for the "require_oauth_only" field.
	DefaultRequireOauthOnly bool
	// DefaultRequirePrivacySet holds the default value on creation for the "require_privacy_set" field.
	DefaultRequirePrivacySet bool
	// DefaultDefaultMappedModel holds the default value on creation for the "default_mapped_model" field.
	DefaultDefaultMappedModel string
	// DefaultMappedModelValidator is a validator for the "default_mapped_model" field. It is called by the builders before save.
	DefaultMappedModelValidator func(string) error
	// DefaultModelsListConfig holds the default value on creation for the "models_list_config" field.
	DefaultModelsListConfig accessview.GroupModelsListConfig
	// DefaultAvailabilityProbeConfig holds the default value on creation for the "availability_probe_config" field.
	DefaultAvailabilityProbeConfig accessview.GroupAvailabilityProbeConfig
	// DefaultRpmLimit holds the default value on creation for the "rpm_limit" field.
	DefaultRpmLimit int
	// DefaultMaxReasoningEffort holds the default value on creation for the "max_reasoning_effort" field.
	DefaultMaxReasoningEffort string
	// MaxReasoningEffortValidator is a validator for the "max_reasoning_effort" field. It is called by the builders before save.
	MaxReasoningEffortValidator func(string) error
	// DefaultMaxReasoningEffortOverLimit holds the default value on creation for the "max_reasoning_effort_over_limit" field.
	DefaultMaxReasoningEffortOverLimit string
	// MaxReasoningEffortOverLimitValidator is a validator for the "max_reasoning_effort_over_limit" field. It is called by the builders before save.
	MaxReasoningEffortOverLimitValidator func(string) error
	// DefaultReasoningEffortMappings holds the default value on creation for the "reasoning_effort_mappings" field.
	DefaultReasoningEffortMappings []accessview.ReasoningEffortMapping
	// DefaultSessionIsolationEnabled holds the default value on creation for the "session_isolation_enabled" field.
	DefaultSessionIsolationEnabled bool
)

// OrderOption defines the ordering options for the Group queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRateMultiplier orders the results by the rate_multiplier field.
func ByRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplier, opts...).ToFunc()
}

// ByIsExclusive orders the results by the is_exclusive field.
func ByIsExclusive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsExclusive, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDuplicateOperationID orders the results by the duplicate_operation_id field.
func ByDuplicateOperationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuplicateOperationID, opts...).ToFunc()
}

// BySchedulerType orders the results by the scheduler_type field.
func BySchedulerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchedulerType, opts...).ToFunc()
}

// ByDisplayBrand orders the results by the display_brand field.
func ByDisplayBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayBrand, opts...).ToFunc()
}

// ByAllowImageGeneration orders the results by the allow_image_generation field.
func ByAllowImageGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowImageGeneration, opts...).ToFunc()
}

// ByAllowBatchImageGeneration orders the results by the allow_batch_image_generation field.
func ByAllowBatchImageGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowBatchImageGeneration, opts...).ToFunc()
}

// ByClaudeCodeOnly orders the results by the claude_code_only field.
func ByClaudeCodeOnly(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaudeCodeOnly, opts...).ToFunc()
}

// ByFallbackGroupID orders the results by the fallback_group_id field.
func ByFallbackGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFallbackGroupID, opts...).ToFunc()
}

// ByFallbackGroupIDOnInvalidRequest orders the results by the fallback_group_id_on_invalid_request field.
func ByFallbackGroupIDOnInvalidRequest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFallbackGroupIDOnInvalidRequest, opts...).ToFunc()
}

// ByUnavailableFallbackGroupID orders the results by the unavailable_fallback_group_id field.
func ByUnavailableFallbackGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnavailableFallbackGroupID, opts...).ToFunc()
}

// ByModelRoutingEnabled orders the results by the model_routing_enabled field.
func ByModelRoutingEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelRoutingEnabled, opts...).ToFunc()
}

// ByMcpXMLInject orders the results by the mcp_xml_inject field.
func ByMcpXMLInject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMcpXMLInject, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByAllowMessagesDispatch orders the results by the allow_messages_dispatch field.
func ByAllowMessagesDispatch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowMessagesDispatch, opts...).ToFunc()
}

// ByResponsesImagePolicy orders the results by the responses_image_policy field.
func ByResponsesImagePolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponsesImagePolicy, opts...).ToFunc()
}

// ByAllowLive orders the results by the allow_live field.
func ByAllowLive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowLive, opts...).ToFunc()
}

// ByOpenaiFastPolicy orders the results by the openai_fast_policy field.
func ByOpenaiFastPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenaiFastPolicy, opts...).ToFunc()
}

// ByForceOpenaiFast orders the results by the force_openai_fast field.
func ByForceOpenaiFast(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForceOpenaiFast, opts...).ToFunc()
}

// ByRequireOauthOnly orders the results by the require_oauth_only field.
func ByRequireOauthOnly(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequireOauthOnly, opts...).ToFunc()
}

// ByRequirePrivacySet orders the results by the require_privacy_set field.
func ByRequirePrivacySet(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequirePrivacySet, opts...).ToFunc()
}

// ByDefaultMappedModel orders the results by the default_mapped_model field.
func ByDefaultMappedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultMappedModel, opts...).ToFunc()
}

// ByRpmLimit orders the results by the rpm_limit field.
func ByRpmLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRpmLimit, opts...).ToFunc()
}

// ByMaxReasoningEffort orders the results by the max_reasoning_effort field.
func ByMaxReasoningEffort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxReasoningEffort, opts...).ToFunc()
}

// ByMaxReasoningEffortOverLimit orders the results by the max_reasoning_effort_over_limit field.
func ByMaxReasoningEffortOverLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxReasoningEffortOverLimit, opts...).ToFunc()
}

// BySessionIsolationEnabled orders the results by the session_isolation_enabled field.
func BySessionIsolationEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionIsolationEnabled, opts...).ToFunc()
}

// ByAPIKeysCount orders the results by api_keys count.
func ByAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeysStep(), opts...)
	}
}

// ByAPIKeys orders the results by api_keys terms.
func ByAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAPIKeyCompositeGroupsCount orders the results by api_key_composite_groups count.
func ByAPIKeyCompositeGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeyCompositeGroupsStep(), opts...)
	}
}

// ByAPIKeyCompositeGroups orders the results by api_key_composite_groups terms.
func ByAPIKeyCompositeGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyCompositeGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsageLogsCount orders the results by usage_logs count.
func ByUsageLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageLogsStep(), opts...)
	}
}

// ByUsageLogs orders the results by usage_logs terms.
func ByUsageLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProvidersCount orders the results by providers count.
func ByProvidersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProvidersStep(), opts...)
	}
}

// ByProviders orders the results by providers terms.
func ByProviders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProvidersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAllowedUsersCount orders the results by allowed_users count.
func ByAllowedUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAllowedUsersStep(), opts...)
	}
}

// ByAllowedUsers orders the results by allowed_users terms.
func ByAllowedUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAllowedUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDisabledPublicUsersCount orders the results by disabled_public_users count.
func ByDisabledPublicUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDisabledPublicUsersStep(), opts...)
	}
}

// ByDisabledPublicUsers orders the results by disabled_public_users terms.
func ByDisabledPublicUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDisabledPublicUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProviderGroupsCount orders the results by provider_groups count.
func ByProviderGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProviderGroupsStep(), opts...)
	}
}

// ByProviderGroups orders the results by provider_groups terms.
func ByProviderGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserAllowedGroupsCount orders the results by user_allowed_groups count.
func ByUserAllowedGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserAllowedGroupsStep(), opts...)
	}
}

// ByUserAllowedGroups orders the results by user_allowed_groups terms.
func ByUserAllowedGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserAllowedGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserDisabledPublicGroupsCount orders the results by user_disabled_public_groups count.
func ByUserDisabledPublicGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserDisabledPublicGroupsStep(), opts...)
	}
}

// ByUserDisabledPublicGroups orders the results by user_disabled_public_groups terms.
func ByUserDisabledPublicGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserDisabledPublicGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
	)
}
func newAPIKeyCompositeGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyCompositeGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeyCompositeGroupsTable, APIKeyCompositeGroupsColumn),
	)
}
func newUsageLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
	)
}
func newProvidersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProvidersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ProvidersTable, ProvidersPrimaryKey...),
	)
}
func newAllowedUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AllowedUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, AllowedUsersTable, AllowedUsersPrimaryKey...),
	)
}
func newDisabledPublicUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DisabledPublicUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, DisabledPublicUsersTable, DisabledPublicUsersPrimaryKey...),
	)
}
func newProviderGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderGroupsInverseTable, ProviderGroupsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, ProviderGroupsTable, ProviderGroupsColumn),
	)
}
func newUserAllowedGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserAllowedGroupsInverseTable, UserAllowedGroupsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, UserAllowedGroupsTable, UserAllowedGroupsColumn),
	)
}
func newUserDisabledPublicGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserDisabledPublicGroupsInverseTable, UserDisabledPublicGroupsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, UserDisabledPublicGroupsTable, UserDisabledPublicGroupsColumn),
	)
}
