// Code generated by ent, DO NOT EDIT.

package group

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDescription, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRateMultiplier, v))
}

// IsExclusive applies equality check predicate on the "is_exclusive" field. It's identical to IsExclusiveEQ.
func IsExclusive(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldIsExclusive, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldStatus, v))
}

// DuplicateOperationID applies equality check predicate on the "duplicate_operation_id" field. It's identical to DuplicateOperationIDEQ.
func DuplicateOperationID(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDuplicateOperationID, v))
}

// SchedulerType applies equality check predicate on the "scheduler_type" field. It's identical to SchedulerTypeEQ.
func SchedulerType(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSchedulerType, v))
}

// DisplayBrand applies equality check predicate on the "display_brand" field. It's identical to DisplayBrandEQ.
func DisplayBrand(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDisplayBrand, v))
}

// AllowImageGeneration applies equality check predicate on the "allow_image_generation" field. It's identical to AllowImageGenerationEQ.
func AllowImageGeneration(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowImageGeneration, v))
}

// AllowBatchImageGeneration applies equality check predicate on the "allow_batch_image_generation" field. It's identical to AllowBatchImageGenerationEQ.
func AllowBatchImageGeneration(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowBatchImageGeneration, v))
}

// ClaudeCodeOnly applies equality check predicate on the "claude_code_only" field. It's identical to ClaudeCodeOnlyEQ.
func ClaudeCodeOnly(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldClaudeCodeOnly, v))
}

// FallbackGroupID applies equality check predicate on the "fallback_group_id" field. It's identical to FallbackGroupIDEQ.
func FallbackGroupID(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldFallbackGroupID, v))
}

// FallbackGroupIDOnInvalidRequest applies equality check predicate on the "fallback_group_id_on_invalid_request" field. It's identical to FallbackGroupIDOnInvalidRequestEQ.
func FallbackGroupIDOnInvalidRequest(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldFallbackGroupIDOnInvalidRequest, v))
}

// UnavailableFallbackGroupID applies equality check predicate on the "unavailable_fallback_group_id" field. It's identical to UnavailableFallbackGroupIDEQ.
func UnavailableFallbackGroupID(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUnavailableFallbackGroupID, v))
}

// ModelRoutingEnabled applies equality check predicate on the "model_routing_enabled" field. It's identical to ModelRoutingEnabledEQ.
func ModelRoutingEnabled(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldModelRoutingEnabled, v))
}

// McpXMLInject applies equality check predicate on the "mcp_xml_inject" field. It's identical to McpXMLInjectEQ.
func McpXMLInject(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldMcpXMLInject, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSortOrder, v))
}

// AllowMessagesDispatch applies equality check predicate on the "allow_messages_dispatch" field. It's identical to AllowMessagesDispatchEQ.
func AllowMessagesDispatch(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowMessagesDispatch, v))
}

// ResponsesImagePolicy applies equality check predicate on the "responses_image_policy" field. It's identical to ResponsesImagePolicyEQ.
func ResponsesImagePolicy(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldResponsesImagePolicy, v))
}

// AllowLive applies equality check predicate on the "allow_live" field. It's identical to AllowLiveEQ.
func AllowLive(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowLive, v))
}

// OpenaiFastPolicy applies equality check predicate on the "openai_fast_policy" field. It's identical to OpenaiFastPolicyEQ.
func OpenaiFastPolicy(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldOpenaiFastPolicy, v))
}

// ForceOpenaiFast applies equality check predicate on the "force_openai_fast" field. It's identical to ForceOpenaiFastEQ.
func ForceOpenaiFast(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldForceOpenaiFast, v))
}

// RequireOauthOnly applies equality check predicate on the "require_oauth_only" field. It's identical to RequireOauthOnlyEQ.
func RequireOauthOnly(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRequireOauthOnly, v))
}

// RequirePrivacySet applies equality check predicate on the "require_privacy_set" field. It's identical to RequirePrivacySetEQ.
func RequirePrivacySet(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRequirePrivacySet, v))
}

// DefaultMappedModel applies equality check predicate on the "default_mapped_model" field. It's identical to DefaultMappedModelEQ.
func DefaultMappedModel(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDefaultMappedModel, v))
}

// RpmLimit applies equality check predicate on the "rpm_limit" field. It's identical to RpmLimitEQ.
func RpmLimit(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRpmLimit, v))
}

// MaxReasoningEffort applies equality check predicate on the "max_reasoning_effort" field. It's identical to MaxReasoningEffortEQ.
func MaxReasoningEffort(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortOverLimit applies equality check predicate on the "max_reasoning_effort_over_limit" field. It's identical to MaxReasoningEffortOverLimitEQ.
func MaxReasoningEffortOverLimit(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldMaxReasoningEffortOverLimit, v))
}

// SessionIsolationEnabled applies equality check predicate on the "session_isolation_enabled" field. It's identical to SessionIsolationEnabledEQ.
func SessionIsolationEnabled(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSessionIsolationEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldDeletedAt))
}

// LocalizationIsNil applies the IsNil predicate on the "localization" field.
func LocalizationIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldLocalization))
}

// LocalizationNotNil applies the NotNil predicate on the "localization" field.
func LocalizationNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldLocalization))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldDescription, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldRateMultiplier, v))
}

// IsExclusiveEQ applies the EQ predicate on the "is_exclusive" field.
func IsExclusiveEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldIsExclusive, v))
}

// IsExclusiveNEQ applies the NEQ predicate on the "is_exclusive" field.
func IsExclusiveNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldIsExclusive, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldStatus, v))
}

// DuplicateOperationIDEQ applies the EQ predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDNEQ applies the NEQ predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDIn applies the In predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldDuplicateOperationID, vs...))
}

// DuplicateOperationIDNotIn applies the NotIn predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldDuplicateOperationID, vs...))
}

// DuplicateOperationIDGT applies the GT predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDGTE applies the GTE predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDLT applies the LT predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDLTE applies the LTE predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDContains applies the Contains predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDHasPrefix applies the HasPrefix predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDHasSuffix applies the HasSuffix predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDIsNil applies the IsNil predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldDuplicateOperationID))
}

// DuplicateOperationIDNotNil applies the NotNil predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldDuplicateOperationID))
}

// DuplicateOperationIDEqualFold applies the EqualFold predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldDuplicateOperationID, v))
}

// DuplicateOperationIDContainsFold applies the ContainsFold predicate on the "duplicate_operation_id" field.
func DuplicateOperationIDContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldDuplicateOperationID, v))
}

// SchedulerTypeEQ applies the EQ predicate on the "scheduler_type" field.
func SchedulerTypeEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSchedulerType, v))
}

// SchedulerTypeNEQ applies the NEQ predicate on the "scheduler_type" field.
func SchedulerTypeNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldSchedulerType, v))
}

// SchedulerTypeIn applies the In predicate on the "scheduler_type" field.
func SchedulerTypeIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldSchedulerType, vs...))
}

// SchedulerTypeNotIn applies the NotIn predicate on the "scheduler_type" field.
func SchedulerTypeNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldSchedulerType, vs...))
}

// SchedulerTypeGT applies the GT predicate on the "scheduler_type" field.
func SchedulerTypeGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldSchedulerType, v))
}

// SchedulerTypeGTE applies the GTE predicate on the "scheduler_type" field.
func SchedulerTypeGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldSchedulerType, v))
}

// SchedulerTypeLT applies the LT predicate on the "scheduler_type" field.
func SchedulerTypeLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldSchedulerType, v))
}

// SchedulerTypeLTE applies the LTE predicate on the "scheduler_type" field.
func SchedulerTypeLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldSchedulerType, v))
}

// SchedulerTypeContains applies the Contains predicate on the "scheduler_type" field.
func SchedulerTypeContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldSchedulerType, v))
}

// SchedulerTypeHasPrefix applies the HasPrefix predicate on the "scheduler_type" field.
func SchedulerTypeHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldSchedulerType, v))
}

// SchedulerTypeHasSuffix applies the HasSuffix predicate on the "scheduler_type" field.
func SchedulerTypeHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldSchedulerType, v))
}

// SchedulerTypeEqualFold applies the EqualFold predicate on the "scheduler_type" field.
func SchedulerTypeEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldSchedulerType, v))
}

// SchedulerTypeContainsFold applies the ContainsFold predicate on the "scheduler_type" field.
func SchedulerTypeContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldSchedulerType, v))
}

// DisplayBrandEQ applies the EQ predicate on the "display_brand" field.
func DisplayBrandEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDisplayBrand, v))
}

// DisplayBrandNEQ applies the NEQ predicate on the "display_brand" field.
func DisplayBrandNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldDisplayBrand, v))
}

// DisplayBrandIn applies the In predicate on the "display_brand" field.
func DisplayBrandIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldDisplayBrand, vs...))
}

// DisplayBrandNotIn applies the NotIn predicate on the "display_brand" field.
func DisplayBrandNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldDisplayBrand, vs...))
}

// DisplayBrandGT applies the GT predicate on the "display_brand" field.
func DisplayBrandGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldDisplayBrand, v))
}

// DisplayBrandGTE applies the GTE predicate on the "display_brand" field.
func DisplayBrandGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldDisplayBrand, v))
}

// DisplayBrandLT applies the LT predicate on the "display_brand" field.
func DisplayBrandLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldDisplayBrand, v))
}

// DisplayBrandLTE applies the LTE predicate on the "display_brand" field.
func DisplayBrandLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldDisplayBrand, v))
}

// DisplayBrandContains applies the Contains predicate on the "display_brand" field.
func DisplayBrandContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldDisplayBrand, v))
}

// DisplayBrandHasPrefix applies the HasPrefix predicate on the "display_brand" field.
func DisplayBrandHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldDisplayBrand, v))
}

// DisplayBrandHasSuffix applies the HasSuffix predicate on the "display_brand" field.
func DisplayBrandHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldDisplayBrand, v))
}

// DisplayBrandEqualFold applies the EqualFold predicate on the "display_brand" field.
func DisplayBrandEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldDisplayBrand, v))
}

// DisplayBrandContainsFold applies the ContainsFold predicate on the "display_brand" field.
func DisplayBrandContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldDisplayBrand, v))
}

// AllowImageGenerationEQ applies the EQ predicate on the "allow_image_generation" field.
func AllowImageGenerationEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowImageGeneration, v))
}

// AllowImageGenerationNEQ applies the NEQ predicate on the "allow_image_generation" field.
func AllowImageGenerationNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldAllowImageGeneration, v))
}

// AllowBatchImageGenerationEQ applies the EQ predicate on the "allow_batch_image_generation" field.
func AllowBatchImageGenerationEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowBatchImageGeneration, v))
}

// AllowBatchImageGenerationNEQ applies the NEQ predicate on the "allow_batch_image_generation" field.
func AllowBatchImageGenerationNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldAllowBatchImageGeneration, v))
}

// RoutingPolicyIsNil applies the IsNil predicate on the "routing_policy" field.
func RoutingPolicyIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldRoutingPolicy))
}

// RoutingPolicyNotNil applies the NotNil predicate on the "routing_policy" field.
func RoutingPolicyNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldRoutingPolicy))
}

// ClaudeCodeOnlyEQ applies the EQ predicate on the "claude_code_only" field.
func ClaudeCodeOnlyEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldClaudeCodeOnly, v))
}

// ClaudeCodeOnlyNEQ applies the NEQ predicate on the "claude_code_only" field.
func ClaudeCodeOnlyNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldClaudeCodeOnly, v))
}

// FallbackGroupIDEQ applies the EQ predicate on the "fallback_group_id" field.
func FallbackGroupIDEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldFallbackGroupID, v))
}

// FallbackGroupIDNEQ applies the NEQ predicate on the "fallback_group_id" field.
func FallbackGroupIDNEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldFallbackGroupID, v))
}

// FallbackGroupIDIn applies the In predicate on the "fallback_group_id" field.
func FallbackGroupIDIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldFallbackGroupID, vs...))
}

// FallbackGroupIDNotIn applies the NotIn predicate on the "fallback_group_id" field.
func FallbackGroupIDNotIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldFallbackGroupID, vs...))
}

// FallbackGroupIDGT applies the GT predicate on the "fallback_group_id" field.
func FallbackGroupIDGT(v int64) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldFallbackGroupID, v))
}

// FallbackGroupIDGTE applies the GTE predicate on the "fallback_group_id" field.
func FallbackGroupIDGTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldFallbackGroupID, v))
}

// FallbackGroupIDLT applies the LT predicate on the "fallback_group_id" field.
func FallbackGroupIDLT(v int64) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldFallbackGroupID, v))
}

// FallbackGroupIDLTE applies the LTE predicate on the "fallback_group_id" field.
func FallbackGroupIDLTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldFallbackGroupID, v))
}

// FallbackGroupIDIsNil applies the IsNil predicate on the "fallback_group_id" field.
func FallbackGroupIDIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldFallbackGroupID))
}

// FallbackGroupIDNotNil applies the NotNil predicate on the "fallback_group_id" field.
func FallbackGroupIDNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldFallbackGroupID))
}

// FallbackGroupIDOnInvalidRequestEQ applies the EQ predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldFallbackGroupIDOnInvalidRequest, v))
}

// FallbackGroupIDOnInvalidRequestNEQ applies the NEQ predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestNEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldFallbackGroupIDOnInvalidRequest, v))
}

// FallbackGroupIDOnInvalidRequestIn applies the In predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldFallbackGroupIDOnInvalidRequest, vs...))
}

// FallbackGroupIDOnInvalidRequestNotIn applies the NotIn predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestNotIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldFallbackGroupIDOnInvalidRequest, vs...))
}

// FallbackGroupIDOnInvalidRequestGT applies the GT predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestGT(v int64) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldFallbackGroupIDOnInvalidRequest, v))
}

// FallbackGroupIDOnInvalidRequestGTE applies the GTE predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestGTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldFallbackGroupIDOnInvalidRequest, v))
}

// FallbackGroupIDOnInvalidRequestLT applies the LT predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestLT(v int64) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldFallbackGroupIDOnInvalidRequest, v))
}

// FallbackGroupIDOnInvalidRequestLTE applies the LTE predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestLTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldFallbackGroupIDOnInvalidRequest, v))
}

// FallbackGroupIDOnInvalidRequestIsNil applies the IsNil predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldFallbackGroupIDOnInvalidRequest))
}

// FallbackGroupIDOnInvalidRequestNotNil applies the NotNil predicate on the "fallback_group_id_on_invalid_request" field.
func FallbackGroupIDOnInvalidRequestNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldFallbackGroupIDOnInvalidRequest))
}

// UnavailableFallbackGroupIDEQ applies the EQ predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUnavailableFallbackGroupID, v))
}

// UnavailableFallbackGroupIDNEQ applies the NEQ predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDNEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldUnavailableFallbackGroupID, v))
}

// UnavailableFallbackGroupIDIn applies the In predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldUnavailableFallbackGroupID, vs...))
}

// UnavailableFallbackGroupIDNotIn applies the NotIn predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDNotIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldUnavailableFallbackGroupID, vs...))
}

// UnavailableFallbackGroupIDGT applies the GT predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDGT(v int64) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldUnavailableFallbackGroupID, v))
}

// UnavailableFallbackGroupIDGTE applies the GTE predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDGTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldUnavailableFallbackGroupID, v))
}

// UnavailableFallbackGroupIDLT applies the LT predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDLT(v int64) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldUnavailableFallbackGroupID, v))
}

// UnavailableFallbackGroupIDLTE applies the LTE predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDLTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldUnavailableFallbackGroupID, v))
}

// UnavailableFallbackGroupIDIsNil applies the IsNil predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldUnavailableFallbackGroupID))
}

// UnavailableFallbackGroupIDNotNil applies the NotNil predicate on the "unavailable_fallback_group_id" field.
func UnavailableFallbackGroupIDNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldUnavailableFallbackGroupID))
}

// ModelRoutingIsNil applies the IsNil predicate on the "model_routing" field.
func ModelRoutingIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldModelRouting))
}

// ModelRoutingNotNil applies the NotNil predicate on the "model_routing" field.
func ModelRoutingNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldModelRouting))
}

// ModelRoutingEnabledEQ applies the EQ predicate on the "model_routing_enabled" field.
func ModelRoutingEnabledEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldModelRoutingEnabled, v))
}

// ModelRoutingEnabledNEQ applies the NEQ predicate on the "model_routing_enabled" field.
func ModelRoutingEnabledNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldModelRoutingEnabled, v))
}

// McpXMLInjectEQ applies the EQ predicate on the "mcp_xml_inject" field.
func McpXMLInjectEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldMcpXMLInject, v))
}

// McpXMLInjectNEQ applies the NEQ predicate on the "mcp_xml_inject" field.
func McpXMLInjectNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldMcpXMLInject, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldSortOrder, v))
}

// AllowMessagesDispatchEQ applies the EQ predicate on the "allow_messages_dispatch" field.
func AllowMessagesDispatchEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowMessagesDispatch, v))
}

// AllowMessagesDispatchNEQ applies the NEQ predicate on the "allow_messages_dispatch" field.
func AllowMessagesDispatchNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldAllowMessagesDispatch, v))
}

// ResponsesImagePolicyEQ applies the EQ predicate on the "responses_image_policy" field.
func ResponsesImagePolicyEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyNEQ applies the NEQ predicate on the "responses_image_policy" field.
func ResponsesImagePolicyNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyIn applies the In predicate on the "responses_image_policy" field.
func ResponsesImagePolicyIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldResponsesImagePolicy, vs...))
}

// ResponsesImagePolicyNotIn applies the NotIn predicate on the "responses_image_policy" field.
func ResponsesImagePolicyNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldResponsesImagePolicy, vs...))
}

// ResponsesImagePolicyGT applies the GT predicate on the "responses_image_policy" field.
func ResponsesImagePolicyGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyGTE applies the GTE predicate on the "responses_image_policy" field.
func ResponsesImagePolicyGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyLT applies the LT predicate on the "responses_image_policy" field.
func ResponsesImagePolicyLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyLTE applies the LTE predicate on the "responses_image_policy" field.
func ResponsesImagePolicyLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyContains applies the Contains predicate on the "responses_image_policy" field.
func ResponsesImagePolicyContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyHasPrefix applies the HasPrefix predicate on the "responses_image_policy" field.
func ResponsesImagePolicyHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyHasSuffix applies the HasSuffix predicate on the "responses_image_policy" field.
func ResponsesImagePolicyHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyEqualFold applies the EqualFold predicate on the "responses_image_policy" field.
func ResponsesImagePolicyEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldResponsesImagePolicy, v))
}

// ResponsesImagePolicyContainsFold applies the ContainsFold predicate on the "responses_image_policy" field.
func ResponsesImagePolicyContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldResponsesImagePolicy, v))
}

// AllowLiveEQ applies the EQ predicate on the "allow_live" field.
func AllowLiveEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldAllowLive, v))
}

// AllowLiveNEQ applies the NEQ predicate on the "allow_live" field.
func AllowLiveNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldAllowLive, v))
}

// OpenaiFastPolicyEQ applies the EQ predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyNEQ applies the NEQ predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyIn applies the In predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldOpenaiFastPolicy, vs...))
}

// OpenaiFastPolicyNotIn applies the NotIn predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldOpenaiFastPolicy, vs...))
}

// OpenaiFastPolicyGT applies the GT predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyGTE applies the GTE predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyLT applies the LT predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyLTE applies the LTE predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyContains applies the Contains predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyHasPrefix applies the HasPrefix predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyHasSuffix applies the HasSuffix predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyEqualFold applies the EqualFold predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldOpenaiFastPolicy, v))
}

// OpenaiFastPolicyContainsFold applies the ContainsFold predicate on the "openai_fast_policy" field.
func OpenaiFastPolicyContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldOpenaiFastPolicy, v))
}

// ForceOpenaiFastEQ applies the EQ predicate on the "force_openai_fast" field.
func ForceOpenaiFastEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldForceOpenaiFast, v))
}

// ForceOpenaiFastNEQ applies the NEQ predicate on the "force_openai_fast" field.
func ForceOpenaiFastNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldForceOpenaiFast, v))
}

// RequireOauthOnlyEQ applies the EQ predicate on the "require_oauth_only" field.
func RequireOauthOnlyEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRequireOauthOnly, v))
}

// RequireOauthOnlyNEQ applies the NEQ predicate on the "require_oauth_only" field.
func RequireOauthOnlyNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldRequireOauthOnly, v))
}

// RequirePrivacySetEQ applies the EQ predicate on the "require_privacy_set" field.
func RequirePrivacySetEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRequirePrivacySet, v))
}

// RequirePrivacySetNEQ applies the NEQ predicate on the "require_privacy_set" field.
func RequirePrivacySetNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldRequirePrivacySet, v))
}

// DefaultMappedModelEQ applies the EQ predicate on the "default_mapped_model" field.
func DefaultMappedModelEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldDefaultMappedModel, v))
}

// DefaultMappedModelNEQ applies the NEQ predicate on the "default_mapped_model" field.
func DefaultMappedModelNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldDefaultMappedModel, v))
}

// DefaultMappedModelIn applies the In predicate on the "default_mapped_model" field.
func DefaultMappedModelIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldDefaultMappedModel, vs...))
}

// DefaultMappedModelNotIn applies the NotIn predicate on the "default_mapped_model" field.
func DefaultMappedModelNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldDefaultMappedModel, vs...))
}

// DefaultMappedModelGT applies the GT predicate on the "default_mapped_model" field.
func DefaultMappedModelGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldDefaultMappedModel, v))
}

// DefaultMappedModelGTE applies the GTE predicate on the "default_mapped_model" field.
func DefaultMappedModelGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldDefaultMappedModel, v))
}

// DefaultMappedModelLT applies the LT predicate on the "default_mapped_model" field.
func DefaultMappedModelLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldDefaultMappedModel, v))
}

// DefaultMappedModelLTE applies the LTE predicate on the "default_mapped_model" field.
func DefaultMappedModelLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldDefaultMappedModel, v))
}

// DefaultMappedModelContains applies the Contains predicate on the "default_mapped_model" field.
func DefaultMappedModelContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldDefaultMappedModel, v))
}

// DefaultMappedModelHasPrefix applies the HasPrefix predicate on the "default_mapped_model" field.
func DefaultMappedModelHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldDefaultMappedModel, v))
}

// DefaultMappedModelHasSuffix applies the HasSuffix predicate on the "default_mapped_model" field.
func DefaultMappedModelHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldDefaultMappedModel, v))
}

// DefaultMappedModelEqualFold applies the EqualFold predicate on the "default_mapped_model" field.
func DefaultMappedModelEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldDefaultMappedModel, v))
}

// DefaultMappedModelContainsFold applies the ContainsFold predicate on the "default_mapped_model" field.
func DefaultMappedModelContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldDefaultMappedModel, v))
}

// RpmLimitEQ applies the EQ predicate on the "rpm_limit" field.
func RpmLimitEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRpmLimit, v))
}

// RpmLimitNEQ applies the NEQ predicate on the "rpm_limit" field.
func RpmLimitNEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldRpmLimit, v))
}

// RpmLimitIn applies the In predicate on the "rpm_limit" field.
func RpmLimitIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldRpmLimit, vs...))
}

// RpmLimitNotIn applies the NotIn predicate on the "rpm_limit" field.
func RpmLimitNotIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldRpmLimit, vs...))
}

// RpmLimitGT applies the GT predicate on the "rpm_limit" field.
func RpmLimitGT(v int) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldRpmLimit, v))
}

// RpmLimitGTE applies the GTE predicate on the "rpm_limit" field.
func RpmLimitGTE(v int) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldRpmLimit, v))
}

// RpmLimitLT applies the LT predicate on the "rpm_limit" field.
func RpmLimitLT(v int) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldRpmLimit, v))
}

// RpmLimitLTE applies the LTE predicate on the "rpm_limit" field.
func RpmLimitLTE(v int) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldRpmLimit, v))
}

// MaxReasoningEffortEQ applies the EQ predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortNEQ applies the NEQ predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortIn applies the In predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldMaxReasoningEffort, vs...))
}

// MaxReasoningEffortNotIn applies the NotIn predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldMaxReasoningEffort, vs...))
}

// MaxReasoningEffortGT applies the GT predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortGTE applies the GTE predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortLT applies the LT predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortLTE applies the LTE predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortContains applies the Contains predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortHasPrefix applies the HasPrefix predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortHasSuffix applies the HasSuffix predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortEqualFold applies the EqualFold predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortContainsFold applies the ContainsFold predicate on the "max_reasoning_effort" field.
func MaxReasoningEffortContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldMaxReasoningEffort, v))
}

// MaxReasoningEffortOverLimitEQ applies the EQ predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitNEQ applies the NEQ predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitIn applies the In predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldMaxReasoningEffortOverLimit, vs...))
}

// MaxReasoningEffortOverLimitNotIn applies the NotIn predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldMaxReasoningEffortOverLimit, vs...))
}

// MaxReasoningEffortOverLimitGT applies the GT predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitGTE applies the GTE predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitLT applies the LT predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitLTE applies the LTE predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitContains applies the Contains predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitHasPrefix applies the HasPrefix predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitHasSuffix applies the HasSuffix predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitEqualFold applies the EqualFold predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldMaxReasoningEffortOverLimit, v))
}

// MaxReasoningEffortOverLimitContainsFold applies the ContainsFold predicate on the "max_reasoning_effort_over_limit" field.
func MaxReasoningEffortOverLimitContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldMaxReasoningEffortOverLimit, v))
}

// SessionIsolationEnabledEQ applies the EQ predicate on the "session_isolation_enabled" field.
func SessionIsolationEnabledEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSessionIsolationEnabled, v))
}

// SessionIsolationEnabledNEQ applies the NEQ predicate on the "session_isolation_enabled" field.
func SessionIsolationEnabledNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldSessionIsolationEnabled, v))
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKeyCompositeGroups applies the HasEdge predicate on the "api_key_composite_groups" edge.
func HasAPIKeyCompositeGroups() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeyCompositeGroupsTable, APIKeyCompositeGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyCompositeGroupsWith applies the HasEdge predicate on the "api_key_composite_groups" edge with a given conditions (other predicates).
func HasAPIKeyCompositeGroupsWith(preds ...predicate.APIKeyCompositeGroup) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newAPIKeyCompositeGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviders applies the HasEdge predicate on the "providers" edge.
func HasProviders() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ProvidersTable, ProvidersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProvidersWith applies the HasEdge predicate on the "providers" edge with a given conditions (other predicates).
func HasProvidersWith(preds ...predicate.Provider) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newProvidersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAllowedUsers applies the HasEdge predicate on the "allowed_users" edge.
func HasAllowedUsers() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AllowedUsersTable, AllowedUsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAllowedUsersWith applies the HasEdge predicate on the "allowed_users" edge with a given conditions (other predicates).
func HasAllowedUsersWith(preds ...predicate.User) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newAllowedUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDisabledPublicUsers applies the HasEdge predicate on the "disabled_public_users" edge.
func HasDisabledPublicUsers() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, DisabledPublicUsersTable, DisabledPublicUsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDisabledPublicUsersWith applies the HasEdge predicate on the "disabled_public_users" edge with a given conditions (other predicates).
func HasDisabledPublicUsersWith(preds ...predicate.User) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newDisabledPublicUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderGroups applies the HasEdge predicate on the "provider_groups" edge.
func HasProviderGroups() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ProviderGroupsTable, ProviderGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderGroupsWith applies the HasEdge predicate on the "provider_groups" edge with a given conditions (other predicates).
func HasProviderGroupsWith(preds ...predicate.ProviderGroup) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newProviderGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserAllowedGroups applies the HasEdge predicate on the "user_allowed_groups" edge.
func HasUserAllowedGroups() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, UserAllowedGroupsTable, UserAllowedGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserAllowedGroupsWith applies the HasEdge predicate on the "user_allowed_groups" edge with a given conditions (other predicates).
func HasUserAllowedGroupsWith(preds ...predicate.UserAllowedGroup) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newUserAllowedGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserDisabledPublicGroups applies the HasEdge predicate on the "user_disabled_public_groups" edge.
func HasUserDisabledPublicGroups() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, UserDisabledPublicGroupsTable, UserDisabledPublicGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserDisabledPublicGroupsWith applies the HasEdge predicate on the "user_disabled_public_groups" edge with a given conditions (other predicates).
func HasUserDisabledPublicGroupsWith(preds ...predicate.UserDisabledPublicGroup) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newUserDisabledPublicGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Group) predicate.Group {
	return predicate.Group(sql.NotPredicates(p))
}
